// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Nexus.Api.Data;
using Nexus.Api.Entities;

namespace Nexus.Api.Services;

public sealed record EventRegistrationError(string Code, string Message, int Status, string? Field = null);
public sealed record EventRegistrationResult(object? Data, EventRegistrationError? Error = null, int Status = 200) { public bool Succeeded => Error is null; }

public sealed class EventRegistrationLifecycleService
{
    private readonly NexusDbContext _db;
    public EventRegistrationLifecycleService(NexusDbContext db) => _db = db;

    public Task<EventRegistrationResult> ConfirmAsync(int tenant, int eventId, int userId, string key, CancellationToken ct) => RegistrationAsync(tenant, eventId, userId, "confirmed", key, null, ct);
    public Task<EventRegistrationResult> WithdrawAsync(int tenant, int eventId, int userId, string key, string? reason, CancellationToken ct) => RegistrationAsync(tenant, eventId, userId, "cancelled", key, reason, ct);

    public async Task<EventRegistrationResult> JoinWaitlistAsync(int tenant, int eventId, int userId, string key, CancellationToken ct)
    {
        var keyError = ValidateKey(key); if (keyError is not null) return keyError; await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, userId, true, ct); if (context.Error is not null) return context; var (evt, _) = ((Event, User))context.Data!; var id = Identity("waitlist.join", tenant, eventId, userId, key);
        var replay = await _db.EventWaitlistEntryHistory.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.IdempotencyKey == id, ct); if (replay is not null) { await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, false, true, replay.Id, false, ct); }
        var confirmed = await _db.EventRegistrations.IgnoreQueryFilters().AnyAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == userId && x.CapacityPoolKey == "event" && x.RegistrationState == "confirmed", ct); if (confirmed) return Conflict("EVENT_REGISTRATION_CONFLICT"); var capacity = await CapacityAsync(evt, ct); if (capacity.Limit is null || !capacity.IsFull) return Conflict("EVENT_WAITLIST_FINITE_CAPACITY_REQUIRED");
        var now = DateTime.UtcNow; var row = await _db.EventWaitlistEntries.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == userId && x.CapacityPoolKey == "event", ct); string? from = row?.QueueState; if (row is not null && row.QueueState is "waiting" or "offered") { await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, false, false, null, false, ct); }
        if (row is null) { var sequence = (await _db.EventWaitlistEntries.IgnoreQueryFilters().Where(x => x.TenantId == tenant && x.EventId == eventId && x.CapacityPoolKey == "event").MaxAsync(x => (long?)x.QueueSequence, ct) ?? 0) + 1; row = new EventWaitlistEntry { TenantId = tenant, EventId = eventId, UserId = userId, QueueSequence = sequence, QueueState = "waiting", StateChangedAt = now, StateChangedBy = userId, CreatedAt = now, UpdatedAt = now }; _db.EventWaitlistEntries.Add(row); await _db.SaveChangesAsync(ct); } else { row.QueueState = "waiting"; row.QueueVersion++; row.StateChangedAt = now; row.StateChangedBy = userId; row.OfferedAt = null; row.OfferExpiresAt = null; row.OfferTokenHash = null; row.OfferTokenUsedAt = null; row.CancelledAt = null; row.UpdatedAt = now; }
        var history = WaitHistory(row, "joined", from, "waiting", userId, id, null, now); _db.EventWaitlistEntryHistory.Add(history); AddOutbox(evt, "waitlist", row.QueueVersion, "event.waitlist.joined", id, new { user_id = userId, queue_sequence = row.QueueSequence }, now); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, true, false, history.Id, false, ct, 201);
    }

    public async Task<EventRegistrationResult> LeaveWaitlistAsync(int tenant, int eventId, int userId, string key, string? reason, CancellationToken ct)
    {
        var keyError = ValidateKey(key); if (keyError is not null) return keyError; if (reason?.Length > 4000) return Validation("reason"); await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, userId, false, ct); if (context.Error is not null) return context; var (evt, _) = ((Event, User))context.Data!; var id = Identity("waitlist.cancel", tenant, eventId, userId, key); var replay = await _db.EventWaitlistEntryHistory.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.IdempotencyKey == id, ct); if (replay is not null) { await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, false, true, replay.Id, false, ct); }
        var row = await _db.EventWaitlistEntries.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == userId && x.CapacityPoolKey == "event", ct); if (row is null || row.QueueState is not ("waiting" or "offered")) return Missing("EVENT_WAITLIST_ENTRY_NOT_FOUND"); var wasOffered = row.QueueState == "offered"; var from = row.QueueState; var now = DateTime.UtcNow; row.QueueState = "cancelled"; row.QueueVersion++; row.StateChangedAt = now; row.StateChangedBy = userId; row.CancelledAt = now; row.OfferTokenHash = null; row.OfferExpiresAt = null; row.UpdatedAt = now; var history = WaitHistory(row, "cancelled", from, "cancelled", userId, id, reason, now); _db.EventWaitlistEntryHistory.Add(history); var offered = wasOffered ? await OfferNextAsync(evt, userId, now, ct) : null; AddOutbox(evt, "waitlist", row.QueueVersion, "event.waitlist.cancelled", id, new { user_id = userId, next_offer_created = offered is not null }, now); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, true, false, history.Id, offered is not null, ct);
    }

    public async Task<EventRegistrationResult> AcceptOfferAsync(int tenant, int eventId, int userId, string key, string? token, CancellationToken ct)
    {
        var keyError = ValidateKey(key); if (keyError is not null) return keyError; if (token is { Length: > 512 } || token is not null && string.IsNullOrWhiteSpace(token)) return Validation("token"); await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, userId, true, ct); if (context.Error is not null) return context; var (evt, _) = ((Event, User))context.Data!; var id = Identity("waitlist.accept", tenant, eventId, userId, key); var replay = await _db.EventWaitlistEntryHistory.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.IdempotencyKey == id, ct); if (replay is not null) { await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, false, true, replay.Id, false, ct); }
        var row = await _db.EventWaitlistEntries.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == userId && x.CapacityPoolKey == "event", ct); if (row is null || row.QueueState != "offered" || row.OfferExpiresAt <= DateTime.UtcNow || row.OfferTokenUsedAt is not null || string.IsNullOrWhiteSpace(row.OfferTokenHash)) return Conflict("EVENT_WAITLIST_OFFER_NOT_ACTIVE"); if (token is not null && !CryptographicOperations.FixedTimeEquals(Convert.FromHexString(row.OfferTokenHash), SHA256.HashData(Encoding.UTF8.GetBytes(token.Trim())))) return Validation("token");
        var now = DateTime.UtcNow; var registration = await _db.EventRegistrations.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == userId && x.CapacityPoolKey == "event", ct); var regFrom = registration?.RegistrationState; if (registration is null) { registration = new EventRegistration { TenantId = tenant, EventId = eventId, UserId = userId, RegistrationState = "confirmed", StateChangedAt = now, StateChangedBy = userId, ConfirmedAt = now, CreatedAt = now, UpdatedAt = now }; _db.EventRegistrations.Add(registration); await _db.SaveChangesAsync(ct); } else { registration.RegistrationState = "confirmed"; registration.RegistrationVersion++; registration.StateChangedAt = now; registration.StateChangedBy = userId; registration.ConfirmedAt = now; registration.CancelledAt = null; registration.UpdatedAt = now; }
        var regHistory = RegHistory(registration, "confirmed_from_waitlist", regFrom, "confirmed", userId, Identity("registration.offer", tenant, eventId, userId, key), null, now); _db.EventRegistrationHistory.Add(regHistory); row.QueueState = "accepted"; row.QueueVersion++; row.StateChangedAt = now; row.StateChangedBy = userId; row.OfferTokenUsedAt = now; row.AcceptedAt = now; row.AcceptedRegistrationId = registration.Id; row.UpdatedAt = now; var history = WaitHistory(row, "accepted", "offered", "accepted", userId, id, null, now); _db.EventWaitlistEntryHistory.Add(history); AddOutbox(evt, "waitlist", row.QueueVersion, "event.waitlist.accepted", id, new { user_id = userId, registration_id = registration.Id }, now); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, true, false, history.Id, false, ct);
    }

    private async Task<EventRegistrationResult> RegistrationAsync(int tenant, int eventId, int userId, string target, string key, string? reason, CancellationToken ct)
    {
        var keyError = ValidateKey(key); if (keyError is not null) return keyError; if (reason?.Length > 4000) return Validation("reason"); await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, userId, target == "confirmed", ct); if (context.Error is not null) return context; var (evt, _) = ((Event, User))context.Data!; var action = target == "confirmed" ? "confirmed" : "cancelled"; var id = Identity("registration." + action, tenant, eventId, userId, key); var replay = await _db.EventRegistrationHistory.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.IdempotencyKey == id, ct); if (replay is not null) { await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, false, true, replay.Id, false, ct); }
        var row = await _db.EventRegistrations.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == userId && x.CapacityPoolKey == "event", ct); var from = row?.RegistrationState; if (from == target) { await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, false, false, null, false, ct); } if (target == "cancelled" && row is null) return Missing("EVENT_REGISTRATION_MEMBER_NOT_FOUND"); if (target == "confirmed") { var capacity = await CapacityAsync(evt, ct); if (capacity.IsFull) return Conflict("EVENT_CAPACITY_FULL"); }
        var now = DateTime.UtcNow; if (row is null) { row = new EventRegistration { TenantId = tenant, EventId = eventId, UserId = userId, RegistrationState = target, StateChangedAt = now, StateChangedBy = userId, ConfirmedAt = target == "confirmed" ? now : null, CancelledAt = target == "cancelled" ? now : null, CreatedAt = now, UpdatedAt = now }; _db.EventRegistrations.Add(row); await _db.SaveChangesAsync(ct); } else { row.RegistrationState = target; row.RegistrationVersion++; row.StateChangedAt = now; row.StateChangedBy = userId; row.ConfirmedAt = target == "confirmed" ? now : row.ConfirmedAt; row.CancelledAt = target == "cancelled" ? now : null; row.UpdatedAt = now; }
        var history = RegHistory(row, action, from, target, userId, id, reason, now); _db.EventRegistrationHistory.Add(history); EventWaitlistEntry? offered = target == "cancelled" ? await OfferNextAsync(evt, userId, now, ct) : null; AddOutbox(evt, "registration", row.RegistrationVersion, "event.registration." + action, id, new { user_id = userId, released_capacity = target == "cancelled", next_offer_created = offered is not null }, now); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await ResponseAsync(evt, userId, true, false, history.Id, offered is not null, ct, released: target == "cancelled");
    }

    private async Task<EventWaitlistEntry?> OfferNextAsync(Event evt, int actor, DateTime now, CancellationToken ct) { var next = await _db.EventWaitlistEntries.IgnoreQueryFilters().Where(x => x.TenantId == evt.TenantId && x.EventId == evt.Id && x.CapacityPoolKey == "event" && x.QueueState == "waiting").OrderBy(x => x.QueueSequence).ThenBy(x => x.Id).FirstOrDefaultAsync(ct); if (next is null) return null; var token = Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant(); next.QueueState = "offered"; next.QueueVersion++; next.StateChangedAt = now; next.StateChangedBy = actor; next.OfferedAt = now; next.OfferExpiresAt = now.AddHours(24); next.OfferTokenHash = Hash(token); next.UpdatedAt = now; _db.EventWaitlistEntryHistory.Add(WaitHistory(next, "offered", "waiting", "offered", actor, Identity("waitlist.offer", evt.TenantId, evt.Id, next.UserId, next.QueueVersion.ToString()), null, now)); return next; }
    private async Task<EventRegistrationResult> ContextAsync(int tenant, int eventId, int userId, bool eligible, CancellationToken ct) { var user = await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.Id == userId && x.IsActive, ct); if (user is null) return Missing("EVENT_REGISTRATION_MEMBER_NOT_FOUND"); var evt = await _db.Events.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.Id == eventId, ct); if (evt is null) return Missing("EVENT_NOT_FOUND"); if (eligible && (evt.StartsAt <= DateTime.UtcNow || evt.PublicationStatus is "archived" or "rejected" || evt.OperationalStatus is "cancelled" or "completed")) return Conflict("EVENT_REGISTRATION_CLOSED"); return new((evt, user)); }
    private async Task<(int? Limit, int Confirmed, int? Remaining, bool IsFull, int Waitlist)> CapacityAsync(Event evt, CancellationToken ct) { var confirmed = await _db.EventRegistrations.IgnoreQueryFilters().CountAsync(x => x.TenantId == evt.TenantId && x.EventId == evt.Id && x.CapacityPoolKey == "event" && x.RegistrationState == "confirmed", ct); var wait = await _db.EventWaitlistEntries.IgnoreQueryFilters().CountAsync(x => x.TenantId == evt.TenantId && x.EventId == evt.Id && x.CapacityPoolKey == "event" && (x.QueueState == "waiting" || x.QueueState == "offered"), ct); int? remaining = evt.MaxAttendees is null ? null : Math.Max(0, evt.MaxAttendees.Value - confirmed); return (evt.MaxAttendees, confirmed, remaining, evt.MaxAttendees is not null && remaining == 0, wait); }
    private async Task<EventRegistrationResult> ResponseAsync(Event evt, int userId, bool changed, bool replay, long? history, bool offered, CancellationToken ct, int status = 200, bool released = false) { var reg = await _db.EventRegistrations.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == evt.TenantId && x.EventId == evt.Id && x.UserId == userId && x.CapacityPoolKey == "event", ct); var wait = await _db.EventWaitlistEntries.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == evt.TenantId && x.EventId == evt.Id && x.UserId == userId && x.CapacityPoolKey == "event", ct); var attendance = await _db.EventAttendance.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == evt.TenantId && x.EventId == evt.Id && x.UserId == userId, ct); var cap = await CapacityAsync(evt, ct); var waitState = wait?.QueueState; var registrationState = waitState is "waiting" or "offered" ? waitState == "waiting" ? "waitlisted" : "offered" : reg?.RegistrationState ?? "none"; var relationship = new { engagement = new { state = "none", can_change = true }, registration = new { state = registrationState, waitlist_position = waitState is "waiting" or "offered" ? wait!.QueueSequence : (long?)null, can_register = evt.StartsAt > DateTime.UtcNow && reg?.RegistrationState != "confirmed" && !cap.IsFull, can_withdraw = reg?.RegistrationState is "confirmed" or "pending" or "invited", can_join_waitlist = evt.StartsAt > DateTime.UtcNow && cap.Limit is not null && cap.IsFull && waitState is not ("waiting" or "offered"), can_leave_waitlist = waitState is "waiting" or "offered" }, waitlist = new { state = wait?.QueueState ?? "none", position = waitState is "waiting" or "offered" ? wait!.QueueSequence : (long?)null, offer_active = waitState == "offered" && wait!.OfferExpiresAt > DateTime.UtcNow }, attendance = new { state = attendance?.AttendanceStatus ?? "not_checked_in", checked_in_at = (string?)null, checked_out_at = (string?)null }, capacity = new { limit = cap.Limit, confirmed = cap.Confirmed, remaining = cap.Remaining, is_full = cap.IsFull, waitlist_count = cap.Waitlist } }; var data = new { contract_version = 2, event_id = evt.Id, relationship, metrics = new { confirmed_count = cap.Confirmed, interested_count = 0, waitlist_count = cap.Waitlist }, status = reg?.RegistrationState, rsvp_counts = new { going = cap.Confirmed, interested = 0 }, waitlist_position = waitState is "waiting" or "offered" ? wait!.QueueSequence : (long?)null, message = (string?)null, mutation = new { changed, idempotent_replay = replay, history_entry_id = history, released_capacity = released, next_offer_created = offered } }; return new(data, Status: status); }
    private static EventRegistrationHistory RegHistory(EventRegistration x, string action, string? from, string to, int actor, string key, string? reason, DateTime now) => new() { TenantId = x.TenantId, EventId = x.EventId, RegistrationId = x.Id, UserId = x.UserId, ActorUserId = actor, CapacityPoolKey = x.CapacityPoolKey, AllocationKey = x.AllocationKey, RegistrationVersion = x.RegistrationVersion, Action = action, FromState = from, ToState = to, IdempotencyKey = key, Reason = reason, Metadata = JsonSerializer.Serialize(new { contract_version = 2 }), CreatedAt = now };
    private static EventWaitlistEntryHistory WaitHistory(EventWaitlistEntry x, string action, string? from, string to, int actor, string key, string? reason, DateTime now) => new() { TenantId = x.TenantId, EventId = x.EventId, WaitlistEntryId = x.Id, UserId = x.UserId, ActorUserId = actor, CapacityPoolKey = x.CapacityPoolKey, AllocationKey = x.AllocationKey, QueueVersion = x.QueueVersion, QueueSequence = x.QueueSequence, Action = action, FromState = from, ToState = to, IdempotencyKey = key, Reason = reason, Metadata = JsonSerializer.Serialize(new { contract_version = 2 }), CreatedAt = now };
    private void AddOutbox(Event evt, string stream, long version, string action, string key, object payload, DateTime now) => _db.EventDomainOutbox.Add(new EventDomainOutbox { TenantId = evt.TenantId, EventId = evt.Id, AggregateStream = stream, AggregateVersion = version, Action = action, IdempotencyKey = "registration:" + key, ProductionMode = "direct", Status = "direct", Payload = JsonSerializer.Serialize(payload), ProcessedAt = now, CreatedAt = now, UpdatedAt = now });
    private Task LockAsync(int tenant, int eventId, CancellationToken ct) => _db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock({tenant}, {eventId})", ct);
    private static string Identity(string action, int tenant, int evt, int user, string key) => Hash($"event-registration:v2:{action}:{tenant}:{evt}:{user}:{key.Trim()}"); private static string Hash(string value) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
    private static EventRegistrationResult? ValidateKey(string key) => string.IsNullOrWhiteSpace(key) || key.Trim().Length > 191 ? Validation("idempotency_key") : null; private static EventRegistrationResult Missing(string code) => new(null, new(code, "Not found", 404)); private static EventRegistrationResult Conflict(string code) => new(null, new(code, "Invalid registration state", 409)); private static EventRegistrationResult Validation(string field) => new(null, new("EVENT_REGISTRATION_VALIDATION_FAILED", "Validation failed", 422, field));
}
