// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using Nexus.Api.Data;
using Nexus.Api.Entities;

namespace Nexus.Api.Services;

public sealed record EventAgendaError(string Code, string Message, int Status, string? Field = null);
public sealed record EventAgendaResult(object? Data, EventAgendaError? Error = null, int Status = 200) { public bool Succeeded => Error is null; }

public sealed class EventAgendaService
{
    private static readonly HashSet<string> Types = ["session", "workshop", "panel", "keynote", "break", "networking", "other"];
    private static readonly HashSet<string> Visibilities = ["public", "registered", "staff"];
    private static readonly HashSet<string> ResourceTypes = ["link", "document", "slides", "download", "stream", "recording"];
    private readonly NexusDbContext _db; private readonly IDataProtector _urls;
    public EventAgendaService(NexusDbContext db, IDataProtectionProvider protection) { _db = db; _urls = protection.CreateProtector("Nexus.EventAgenda.ResourceUrl.v1"); }

    public async Task<EventAgendaResult> ReadAsync(int tenant, int eventId, int actorId, bool includeCancelled, CancellationToken ct)
    {
        var context = await ContextAsync(tenant, eventId, actorId, false, ct); if (!context.Succeeded) return context;
        var (evt, actor, manage, registered) = ((Event, User, bool, bool))context.Data!;
        var sessions = await Query(tenant, eventId).Where(x => includeCancelled && manage || x.Status == "scheduled").OrderBy(x => x.StartsAtUtc).ThenBy(x => x.Position).ThenBy(x => x.Id).ToListAsync(ct);
        sessions = sessions.Where(x => manage || x.Visibility == "public" || x.Visibility == "registered" && registered).ToList();
        return new(await AgendaAsync(evt, actor, manage, registered, sessions, ct));
    }

    public async Task<EventAgendaResult> CreateAsync(int tenant, int eventId, int actorId, JsonElement input, string key, CancellationToken ct)
    {
        var validation = ValidateKey(key); if (validation is not null) return validation; var parsed = ParseSession(input, false); if (!parsed.Succeeded) return parsed;
        var p = (SessionInput)parsed.Data!; var hash = Hash(input);
        await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct);
        var context = await ContextAsync(tenant, eventId, actorId, true, ct); if (!context.Succeeded) return context; var (evt, actor, manage, _) = ((Event, User, bool, bool))context.Data!; if (!manage) return Forbidden();
        var replay = await ReplayAsync(tenant, eventId, actorId, "created", key, hash, ct); if (replay is not null) { await tx.CommitAsync(ct); return replay; }
        if (!WithinEvent(evt, p.Start, p.End)) return Validation("start_at");
        var conflict = await ConflictAsync(tenant, eventId, null, p, ct); if (conflict is not null) return conflict;
        var session = new EventSession { TenantId = tenant, EventId = eventId, Title = p.Title, Description = p.Description, SessionType = p.Type, Visibility = p.Visibility, Capacity = p.Capacity, StartsAtUtc = p.Start, EndsAtUtc = p.End, Timezone = p.Timezone, TrackName = p.Track, RoomName = p.Room, RoomKey = RoomKey(p.Room), Position = p.Position, CreatedBy = actorId, UpdatedBy = actorId };
        _db.EventSessions.Add(session); await _db.SaveChangesAsync(ct); await ReplaceChildrenAsync(session, p, actorId, ct); evt.AgendaVersion++; var history = History(tenant, evt, session.Id, actorId, "created", key, hash, ["session"], [session.Id]); _db.EventSessionHistory.Add(history); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct);
        return new(new { session = await ProjectAsync(session, actor, true, true, ct), agenda_version = evt.AgendaVersion, changed = true, idempotent_replay = false, history_entry_id = history.Id }, Status: 201);
    }

    public async Task<EventAgendaResult> UpdateAsync(int tenant, int eventId, long sessionId, int actorId, long expected, JsonElement input, string key, CancellationToken ct)
    {
        if (expected < 1) return Validation("expected_version"); var validation = ValidateKey(key); if (validation is not null) return validation; var parsed = ParseSession(input, true); if (!parsed.Succeeded) return parsed; var p = (SessionInput)parsed.Data!; var hash = Hash(input);
        await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, actorId, true, ct); if (!context.Succeeded) return context; var (evt, actor, manage, _) = ((Event, User, bool, bool))context.Data!; if (!manage) return Forbidden();
        var replay = await ReplayAsync(tenant, eventId, actorId, "updated", key, hash, ct); if (replay is not null) { await tx.CommitAsync(ct); return replay; }
        var session = await Query(tenant, eventId).SingleOrDefaultAsync(x => x.Id == sessionId, ct); if (session is null) return Missing(); if (session.Version != expected) return Conflict(); if (!WithinEvent(evt, p.Start, p.End)) return Validation("start_at"); var collision = await ConflictAsync(tenant, eventId, sessionId, p, ct); if (collision is not null) return collision;
        session.Title = p.Title; session.Description = p.Description; session.SessionType = p.Type; session.Visibility = p.Visibility; session.Capacity = p.Capacity; session.StartsAtUtc = p.Start; session.EndsAtUtc = p.End; session.Timezone = p.Timezone; session.TrackName = p.Track; session.RoomName = p.Room; session.RoomKey = RoomKey(p.Room); session.Position = p.Position; session.UpdatedBy = actorId; session.UpdatedAt = DateTime.UtcNow; session.Version++;
        await ReplaceChildrenAsync(session, p, actorId, ct); evt.AgendaVersion++; var history = History(tenant, evt, session.Id, actorId, "updated", key, hash, ["session"], [session.Id]); _db.EventSessionHistory.Add(history); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(new { session = await ProjectAsync(session, actor, true, true, ct), agenda_version = evt.AgendaVersion, changed = true, idempotent_replay = false, history_entry_id = history.Id });
    }

    public async Task<EventAgendaResult> CancelAsync(int tenant, int eventId, long sessionId, int actorId, long expected, string? reason, string key, CancellationToken ct)
    {
        if (expected < 1) return Validation("expected_version"); if (string.IsNullOrWhiteSpace(reason) || reason.Trim().Length > 500) return Validation("reason"); var validation = ValidateKey(key); if (validation is not null) return validation; var hash = Hash(new { expected_version = expected, reason = reason.Trim() });
        await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, actorId, true, ct); if (!context.Succeeded) return context; var (evt, actor, manage, _) = ((Event, User, bool, bool))context.Data!; if (!manage) return Forbidden(); var replay = await ReplayAsync(tenant, eventId, actorId, "cancelled", key, hash, ct); if (replay is not null) { await tx.CommitAsync(ct); return replay; }
        var session = await Query(tenant, eventId).SingleOrDefaultAsync(x => x.Id == sessionId, ct); if (session is null) return Missing(); if (session.Version != expected) return Conflict(); session.Status = "cancelled"; session.CancellationReason = Clean(reason); session.CancelledBy = actorId; session.CancelledAt = DateTime.UtcNow; session.UpdatedBy = actorId; session.UpdatedAt = DateTime.UtcNow; session.Version++; evt.AgendaVersion++;
        var history = History(tenant, evt, session.Id, actorId, "cancelled", key, hash, ["status", "cancellation_reason"], [session.Id]); _db.EventSessionHistory.Add(history); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(new { session = await ProjectAsync(session, actor, true, true, ct), agenda_version = evt.AgendaVersion, changed = true, idempotent_replay = false, history_entry_id = history.Id });
    }

    public async Task<EventAgendaResult> ReorderAsync(int tenant, int eventId, int actorId, long expected, long[] ids, string key, CancellationToken ct)
    {
        if (expected < 0) return Validation("expected_agenda_version"); if (ids.Length > 1000 || ids.Any(x => x < 1) || ids.Distinct().Count() != ids.Length) return Validation("ordered_session_ids"); var validation = ValidateKey(key); if (validation is not null) return validation; var hash = Hash(new { expected_agenda_version = expected, ordered_session_ids = ids });
        await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, actorId, true, ct); if (!context.Succeeded) return context; var (evt, actor, manage, _) = ((Event, User, bool, bool))context.Data!; if (!manage) return Forbidden(); var replay = await ReplayAsync(tenant, eventId, actorId, "reordered", key, hash, ct); if (replay is not null) { await tx.CommitAsync(ct); return replay; } if (evt.AgendaVersion != expected) return Conflict();
        var sessions = await Query(tenant, eventId).Where(x => x.Status == "scheduled").OrderBy(x => x.Position).ThenBy(x => x.Id).ToListAsync(ct); if (!sessions.Select(x => x.Id).Order().SequenceEqual(ids.Order())) return Validation("ordered_session_ids"); for (var i = 0; i < ids.Length; i++) { var s = sessions.Single(x => x.Id == ids[i]); s.Position = i; s.Version++; s.UpdatedBy = actorId; s.UpdatedAt = DateTime.UtcNow; } evt.AgendaVersion++; var history = History(tenant, evt, null, actorId, "reordered", key, hash, ["position"], ids); _db.EventSessionHistory.Add(history); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); var projected = new List<object>(); foreach (var s in sessions.OrderBy(x => x.Position)) projected.Add(await ProjectAsync(s, actor, true, true, ct)); return new(new { sessions = projected, agenda_version = evt.AgendaVersion, changed = true, idempotent_replay = false, history_entry_id = history.Id });
    }

    public Task<EventAgendaResult> RegisterAsync(int tenant, int eventId, long sessionId, int actorId, long expected, string key, CancellationToken ct) => RegistrationAsync(tenant, eventId, sessionId, actorId, expected, key, true, ct);
    public Task<EventAgendaResult> WithdrawAsync(int tenant, int eventId, long sessionId, int actorId, long expected, string key, CancellationToken ct) => RegistrationAsync(tenant, eventId, sessionId, actorId, expected, key, false, ct);

    private async Task<EventAgendaResult> RegistrationAsync(int tenant, int eventId, long sessionId, int actorId, long expected, string key, bool register, CancellationToken ct)
    {
        if (expected < 0) return Validation("expected_version"); var validation = ValidateKey(key); if (validation is not null) return validation; var hash = Hash(new { expected_version = expected });
        await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, actorId, true, ct); if (!context.Succeeded) return context; var (evt, actor, manage, confirmed) = ((Event, User, bool, bool))context.Data!; var session = await Query(tenant, eventId).SingleOrDefaultAsync(x => x.Id == sessionId && x.Status == "scheduled", ct); if (session is null) return Missing();
        var replay = await _db.EventSessionRegistrationHistory.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.IdempotencyKey == key, ct); if (replay is not null) { if (replay.RequestHash != hash || replay.EventId != eventId || replay.SessionId != sessionId || replay.UserId != actorId || replay.Action != (register ? "registered" : "withdrawn")) return Conflict(); var existing = await _db.EventSessionRegistrations.IgnoreQueryFilters().SingleAsync(x => x.Id == replay.RegistrationId, ct); await tx.CommitAsync(ct); return new(new { session = await ProjectAsync(session, actor, manage, confirmed, ct), registration_version = existing.Version, changed = false, idempotent_replay = true, history_entry_id = replay.Id }); }
        if (!confirmed || session.Visibility == "staff" || manage) return new(null, new("EVENT_AGENDA_REGISTRATION_REQUIRED", "Registration required", 403));
        var eventRegistration = await _db.EventRegistrations.IgnoreQueryFilters().SingleAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == actorId && x.RegistrationState == "confirmed", ct); var row = await _db.EventSessionRegistrations.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.SessionId == sessionId && x.UserId == actorId, ct);
        if (row is null) { if (!register || expected != 0) return Conflict(); var count = await _db.EventSessionRegistrations.IgnoreQueryFilters().CountAsync(x => x.TenantId == tenant && x.SessionId == sessionId && x.Status == "registered", ct); if (session.Capacity is int cap && count >= cap) return new(null, new("EVENT_AGENDA_SESSION_FULL", "Session is full", 409, "capacity")); row = new() { TenantId = tenant, EventId = eventId, SessionId = sessionId, UserId = actorId, EventRegistrationId = eventRegistration.Id, EventRegistrationVersion = eventRegistration.RegistrationVersion, RegisteredAt = DateTime.UtcNow }; _db.EventSessionRegistrations.Add(row); }
        else { if (row.Version != expected || register && row.Status == "registered" || !register && row.Status != "registered") return Conflict(); row.Version++; row.Status = register ? "registered" : "withdrawn"; row.RegisteredAt = register ? DateTime.UtcNow : row.RegisteredAt; row.WithdrawnAt = register ? null : DateTime.UtcNow; row.EventRegistrationVersion = eventRegistration.RegistrationVersion; row.UpdatedAt = DateTime.UtcNow; if (register) { var count = await _db.EventSessionRegistrations.IgnoreQueryFilters().CountAsync(x => x.TenantId == tenant && x.SessionId == sessionId && x.Status == "registered", ct); if (session.Capacity is int cap && count >= cap) return new(null, new("EVENT_AGENDA_SESSION_FULL", "Session is full", 409, "capacity")); } }
        await _db.SaveChangesAsync(ct); var history = new EventSessionRegistrationHistory { TenantId = tenant, EventId = eventId, SessionId = sessionId, RegistrationId = row.Id, UserId = actorId, EventRegistrationId = eventRegistration.Id, EventRegistrationVersion = eventRegistration.RegistrationVersion, ActorUserId = actorId, RegistrationVersion = row.Version, Action = register ? "registered" : "withdrawn", IdempotencyKey = key, RequestHash = hash }; _db.EventSessionRegistrationHistory.Add(history); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(new { session = await ProjectAsync(session, actor, manage, confirmed, ct), registration_version = row.Version, changed = true, idempotent_replay = false, history_entry_id = history.Id });
    }

    private IQueryable<EventSession> Query(int tenant, int eventId) => _db.EventSessions.IgnoreQueryFilters().Where(x => x.TenantId == tenant && x.EventId == eventId).Include(x => x.Speakers).Include(x => x.Resources);
    private async Task<EventAgendaResult> ContextAsync(int tenant, int eventId, int actorId, bool mutate, CancellationToken ct) { var evt = await _db.Events.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant && x.Id == eventId, ct); if (evt is null) return Missing(); var actor = await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.Id == actorId && x.IsActive, ct); if (actor is null) return Forbidden(); var manage = IsAdmin(actor) || evt.CreatedById == actorId || evt.GroupId is int group && await _db.GroupMembers.IgnoreQueryFilters().AnyAsync(x => x.TenantId == tenant && x.GroupId == group && x.UserId == actorId && x.Status == "active" && (x.Role == "owner" || x.Role == "admin"), ct); var registered = await _db.EventRegistrations.IgnoreQueryFilters().AnyAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == actorId && x.RegistrationState == "confirmed", ct); if (!mutate && evt.PublicationStatus != "published" && !manage) return Forbidden(); if (mutate && (evt.IsCancelled || evt.OperationalStatus == "cancelled")) return Conflict(); return new((evt, actor, manage, registered)); }
    private async Task<object> AgendaAsync(Event evt, User actor, bool manage, bool registered, List<EventSession> sessions, CancellationToken ct) { var items = new List<object>(); foreach (var session in sessions) items.Add(await ProjectAsync(session, actor, manage, registered, ct)); return new { contract_version = 1, event_id = evt.Id, agenda_version = evt.AgendaVersion, timezone = string.IsNullOrWhiteSpace(evt.Timezone) ? "UTC" : evt.Timezone, permissions = new { manage }, sessions = items }; }
    private async Task<object> ProjectAsync(EventSession s, User actor, bool manage, bool eventRegistered, CancellationToken ct) { var regs = await _db.EventSessionRegistrations.IgnoreQueryFilters().AsNoTracking().Where(x => x.TenantId == s.TenantId && x.SessionId == s.Id).ToListAsync(ct); var mine = regs.SingleOrDefault(x => x.UserId == actor.Id); var count = regs.Count(x => x.Status == "registered"); var memberIds = s.Speakers.Where(y => y.UserId != null).Select(y => y.UserId!.Value).ToArray(); var names = await _db.Users.IgnoreQueryFilters().AsNoTracking().Where(x => x.TenantId == s.TenantId && memberIds.Contains(x.Id)).ToDictionaryAsync(x => x.Id, ct); var speakers = s.Speakers.OrderBy(x => x.Position).ThenBy(x => x.Id).Select(x => new { kind = x.UserId is null ? "external" : "member", member_id = x.UserId, display_name = x.UserId is int id && names.TryGetValue(id, out var u) ? Name(u) : x.DisplayName, role = x.RoleLabel, position = x.Position }); var canProtected = manage || eventRegistered; var resources = s.Resources.Where(x => x.Visibility == "public" || x.Visibility == "registered" && canProtected || x.Visibility == "staff" && manage).OrderBy(x => x.Position).ThenBy(x => x.Id).Select(x => Resource(x, canProtected || manage)).Where(x => x is not null); var remaining = s.Capacity is int cap ? Math.Max(0, cap - count) : (int?)null; var state = mine?.Status ?? (eventRegistered && s.Visibility != "staff" && !manage ? "not_registered" : "ineligible"); return new { id = s.Id, version = s.Version, title = Clean(s.Title), description = Clean(s.Description), type = s.SessionType, visibility = s.Visibility, capacity = new { limit = s.Capacity, registered = count, remaining, is_full = remaining == 0 }, registration = new { state, version = mine?.Version ?? 0, can_register = state is "not_registered" or "withdrawn" && remaining != 0, can_withdraw = state == "registered" }, status = s.Status, start_at = Iso(s.StartsAtUtc), end_at = Iso(s.EndsAtUtc), timezone = s.Timezone, track = Clean(s.TrackName), room = Clean(s.RoomName), position = s.Position, cancellation_reason = manage ? Clean(s.CancellationReason) : null, speakers, resources }; }
    private object? Resource(EventSessionResource x, bool authorized) { var protectedMedia = x.ResourceType is "stream" or "recording"; if (protectedMedia && !authorized) return null; string? url = null; try { url = _urls.Unprotect(x.UrlCiphertext); } catch { } if (!SafeUrl(url)) url = null; return new { id = x.Id, type = x.ResourceType, title = Clean(x.Title), visibility = x.Visibility, position = x.Position, @protected = protectedMedia, available = url is not null, url }; }
    private async Task ReplaceChildrenAsync(EventSession s, SessionInput input, int actorId, CancellationToken ct) { var oldSpeakers = await _db.EventSessionSpeakers.IgnoreQueryFilters().Where(x => x.TenantId == s.TenantId && x.SessionId == s.Id).ToListAsync(ct); var oldResources = await _db.EventSessionResources.IgnoreQueryFilters().Where(x => x.TenantId == s.TenantId && x.SessionId == s.Id).ToListAsync(ct); _db.RemoveRange(oldSpeakers); _db.RemoveRange(oldResources); var now = DateTime.UtcNow; _db.EventSessionSpeakers.AddRange(input.Speakers.Select((x, i) => new EventSessionSpeaker { TenantId = s.TenantId, EventId = s.EventId, SessionId = s.Id, UserId = x.MemberId, DisplayName = x.DisplayName, RoleLabel = x.Role, Position = x.Position ?? i, CreatedAt = now, UpdatedAt = now })); _db.EventSessionResources.AddRange(input.Resources.Select((x, i) => new EventSessionResource { TenantId = s.TenantId, EventId = s.EventId, SessionId = s.Id, ResourceType = x.Type, Visibility = x.Visibility, Title = x.Title, UrlCiphertext = _urls.Protect(x.Url), Position = x.Position ?? i, CreatedBy = actorId, UpdatedBy = actorId, CreatedAt = now, UpdatedAt = now })); await _db.SaveChangesAsync(ct); }
    private async Task<EventAgendaResult?> ReplayAsync(int tenant, int eventId, int actorId, string action, string key, string hash, CancellationToken ct) { var h = await _db.EventSessionHistory.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.IdempotencyKey == key, ct); if (h is null) return null; if (h.EventId != eventId || h.ActorUserId != actorId || h.Action != action || h.RequestHash != hash) return Conflict(); var session = h.SessionId is long id ? await Query(tenant, eventId).SingleAsync(x => x.Id == id, ct) : null; var actor = await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleAsync(x => x.TenantId == tenant && x.Id == h.ActorUserId, ct); if (session is not null) return new(new { session = await ProjectAsync(session, actor, true, true, ct), agenda_version = h.AgendaVersion, changed = false, idempotent_replay = true, history_entry_id = h.Id }); var sessions = await Query(tenant, eventId).OrderBy(x => x.Position).ToListAsync(ct); var projected = new List<object>(); foreach (var s in sessions) projected.Add(await ProjectAsync(s, actor, true, true, ct)); return new(new { sessions = projected, agenda_version = h.AgendaVersion, changed = false, idempotent_replay = true, history_entry_id = h.Id }); }
    private async Task<EventAgendaResult?> ConflictAsync(int tenant, int eventId, long? exclude, SessionInput p, CancellationToken ct) { var overlapping = await _db.EventSessions.IgnoreQueryFilters().Where(x => x.TenantId == tenant && x.EventId == eventId && x.Status == "scheduled" && x.Id != exclude && x.StartsAtUtc < p.End && x.EndsAtUtc > p.Start).ToListAsync(ct); if (p.Room is not null && overlapping.Any(x => x.RoomKey == RoomKey(p.Room))) return Conflict(); var memberIds = p.Speakers.Where(x => x.MemberId != null).Select(x => x.MemberId!.Value).ToArray(); if (memberIds.Length > 0 && await _db.EventSessionSpeakers.IgnoreQueryFilters().AnyAsync(x => x.TenantId == tenant && memberIds.Contains(x.UserId ?? 0) && overlapping.Select(y => y.Id).Contains(x.SessionId), ct)) return Conflict(); return null; }
    private sealed record SpeakerInput(int? MemberId, string? DisplayName, string? Role, int? Position); private sealed record ResourceInput(string Type, string Visibility, string Title, string Url, int? Position); private sealed record SessionInput(string Title, string? Description, string Type, string Visibility, int? Capacity, DateTime Start, DateTime End, string Timezone, string? Track, string? Room, int Position, SpeakerInput[] Speakers, ResourceInput[] Resources);
    private static EventAgendaResult ParseSession(JsonElement x, bool update) { try { if (x.ValueKind != JsonValueKind.Object) return Validation("body"); var title = Text(x, "title")?.Trim(); var type = Text(x, "type") ?? Text(x, "session_type") ?? "session"; var visibility = Text(x, "visibility") ?? "public"; var timezone = Text(x, "timezone") ?? "UTC"; if (string.IsNullOrWhiteSpace(title) || title.Length > 191 || !Types.Contains(type) || !Visibilities.Contains(visibility) || !DateTimeOffset.TryParse(Text(x, "start_at"), out var start) || !DateTimeOffset.TryParse(Text(x, "end_at"), out var end) || start >= end || timezone.Length > 64) return Validation("session"); int? capacity = null; if (x.TryGetProperty("capacity", out var cap) && cap.ValueKind != JsonValueKind.Null) { if (!cap.TryGetInt32(out var c) || c < 1) return Validation("capacity"); capacity = c; } var speakers = new List<SpeakerInput>(); if (x.TryGetProperty("speakers", out var ss)) { if (ss.ValueKind != JsonValueKind.Array || ss.GetArrayLength() > 100) return Validation("speakers"); foreach (var s in ss.EnumerateArray()) { var member = IntN(s, "member_id") ?? IntN(s, "user_id"); var display = Text(s, "display_name"); if ((member is null) == string.IsNullOrWhiteSpace(display)) return Validation("speakers"); speakers.Add(new(member, Clean(display), Clean(Text(s, "role")), IntN(s, "position"))); } } var resources = new List<ResourceInput>(); if (x.TryGetProperty("resources", out var rs)) { if (rs.ValueKind != JsonValueKind.Array || rs.GetArrayLength() > 100) return Validation("resources"); foreach (var r in rs.EnumerateArray()) { var rt = Text(r, "type") ?? "link"; var rv = Text(r, "visibility") ?? "public"; var rtitle = Text(r, "title")?.Trim(); var url = Text(r, "url"); if (!ResourceTypes.Contains(rt) || !Visibilities.Contains(rv) || string.IsNullOrWhiteSpace(rtitle) || !SafeUrl(url) || rt is "stream" or "recording" && rv == "public") return Validation("resources"); resources.Add(new(rt, rv, rtitle, url!, IntN(r, "position"))); } } return new(new SessionInput(title, Clean(Text(x, "description")), type, visibility, capacity, start.UtcDateTime, end.UtcDateTime, timezone, Clean(Text(x, "track")), Clean(Text(x, "room")), IntN(x, "position") ?? 0, speakers.ToArray(), resources.ToArray())); } catch { return Validation("body"); } }
    private static EventSessionHistory History(int tenant, Event evt, long? session, int actor, string action, string key, string hash, string[] changed, IEnumerable<long> ids) => new() { TenantId = tenant, EventId = evt.Id, SessionId = session, ActorUserId = actor, AgendaVersion = evt.AgendaVersion, Action = action, IdempotencyKey = key, RequestHash = hash, ChangedFields = JsonSerializer.Serialize(changed), AffectedSessionIds = JsonSerializer.Serialize(ids) };
    private Task LockAsync(int tenant, int eventId, CancellationToken ct) => _db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock({tenant}, {eventId})", ct); private static bool WithinEvent(Event e, DateTime start, DateTime end) => start >= e.StartsAt.ToUniversalTime() && (e.EndsAt is null || end <= e.EndsAt.Value.ToUniversalTime()); private static string? RoomKey(string? room) => string.IsNullOrWhiteSpace(room) ? null : Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(room.Trim().ToLowerInvariant()))).ToLowerInvariant(); private static string Hash(JsonElement x) => Hash(x.GetRawText()); private static string Hash(object x) => Hash(JsonSerializer.Serialize(x)); private static string Hash(string x) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x))).ToLowerInvariant(); private static string Iso(DateTime x) => x.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ss'Z'"); private static string? Text(JsonElement x, string n) => x.TryGetProperty(n, out var p) && p.ValueKind == JsonValueKind.String ? p.GetString() : null; private static int? IntN(JsonElement x, string n) => x.TryGetProperty(n, out var p) && p.TryGetInt32(out var v) && v >= 0 ? v : null; private static string? Clean(string? x) { if (string.IsNullOrWhiteSpace(x)) return null; var value = System.Text.RegularExpressions.Regex.Replace(x, "<[^>]*>", "").Trim(); return value.Length == 0 ? null : value; } private static bool SafeUrl(string? x) => Uri.TryCreate(x, UriKind.Absolute, out var u) && u.Scheme == Uri.UriSchemeHttps && string.IsNullOrEmpty(u.UserInfo) && !string.IsNullOrWhiteSpace(u.Host); private static string Name(User x) => string.Join(' ', new[] { x.FirstName, x.LastName }.Where(s => !string.IsNullOrWhiteSpace(s))); private static bool IsAdmin(User x) => x.IsAdmin || x.IsSuperAdmin || x.IsTenantSuperAdmin || x.IsGod || x.Role is "admin" or "super_admin" or "god";
    private static EventAgendaResult? ValidateKey(string key) => string.IsNullOrWhiteSpace(key) || key.Trim().Length > 191 ? Validation("idempotency_key") : null; private static EventAgendaResult Missing() => new(null, new("EVENT_AGENDA_NOT_FOUND", "Event or session not found", 404)); private static EventAgendaResult Forbidden() => new(null, new("EVENT_AGENDA_FORBIDDEN", "Forbidden", 403)); private static EventAgendaResult Conflict() => new(null, new("EVENT_AGENDA_CONFLICT", "Version or scheduling conflict", 409)); private static EventAgendaResult Validation(string field) => new(null, new("EVENT_AGENDA_VALIDATION_FAILED", "Validation failed", 422, field));
}
