// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Nexus.Api.Data;
using Nexus.Api.Entities;

namespace Nexus.Api.Services;

public sealed record EventCalendarError(string Code, string Message, int Status, string? Field = null);
public sealed record EventCalendarResult(object? Data, object? Meta = null, EventCalendarError? Error = null, int Status = 200) { public bool Succeeded => Error is null; }

public sealed class EventCalendarParityService
{
    private readonly NexusDbContext _db; public EventCalendarParityService(NexusDbContext db) => _db = db;

    public async Task<EventCalendarResult> CalendarAsync(int tenant, int userId, DateOnly from, DateOnly to, string baseUrl, CancellationToken ct)
    {
        if (to <= from || to.DayNumber - from.DayNumber > 366) return RangeError(); var actor = await ActorAsync(tenant, userId, ct); if (actor is null) return Forbidden(); var events = await VisibleRangeAsync(tenant, actor, from.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc), to.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc), null, ct); return new(events.Select(x => Project(x, baseUrl)).ToArray(), new { range = new { from = from.ToString("yyyy-MM-dd"), to = to.ToString("yyyy-MM-dd"), timezone = "UTC" }, identity_free = true, restricted_access_redacted = true });
    }

    public async Task<EventCalendarResult> EventAsync(int tenant, int userId, int eventId, string baseUrl, CancellationToken ct) { var actor = await ActorAsync(tenant, userId, ct); if (actor is null) return Forbidden(); var evt = await VisibleEventAsync(tenant, actor, eventId, ct); return evt is null ? Missing() : new(Project(evt, baseUrl)); }
    public async Task<EventCalendarResult> TokensAsync(int tenant, int userId, CancellationToken ct) { if (await ActorAsync(tenant,userId,ct) is null) return Forbidden(); var rows = await _db.EventCalendarFeedTokens.IgnoreQueryFilters().AsNoTracking().Where(x => x.TenantId == tenant && x.UserId == userId).OrderByDescending(x => x.Id).Take(50).ToListAsync(ct); return new(rows.Select(Token).ToArray(), new { secrets_returned = false }); }

    public async Task<EventCalendarResult> CreateTokenAsync(int tenant, int userId, string? label, string baseUrl, CancellationToken ct)
    {
        label = string.IsNullOrWhiteSpace(label) ? null : label.Trim(); if (label?.Length > 100) return new(null, Error: new("EVENT_CALENDAR_LABEL_INVALID", "Invalid label", 422, "label")); await using var tx = await _db.Database.BeginTransactionAsync(ct); await _db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock({tenant}, {userId})",ct); var actor = await ActorAsync(tenant,userId,ct); if(actor is null)return Forbidden(); if(await _db.EventCalendarFeedTokens.IgnoreQueryFilters().CountAsync(x=>x.TenantId==tenant&&x.UserId==userId&&x.RevokedAt==null,ct)>=10)return new(null,Error:new("EVENT_CALENDAR_TOKEN_LIMIT","Token limit reached",409)); var bytes=RandomNumberGenerator.GetBytes(32); var secret="nxc_"+Convert.ToHexString(bytes).ToLowerInvariant(); var row=new EventCalendarFeedToken{TenantId=tenant,UserId=userId,TokenHash=Hash(secret),TokenPrefix=secret[..12],Label=label,Locale=Locale(actor)}; _db.EventCalendarFeedTokens.Add(row);await _db.SaveChangesAsync(ct);var slug=await _db.Tenants.IgnoreQueryFilters().Where(x=>x.Id==tenant).Select(x=>x.Slug).SingleAsync(ct);await tx.CommitAsync(ct);dynamic data=Token(row);return new(new{id=data.id,label=data.label,token_prefix=data.token_prefix,locale=data.locale,created_at=data.created_at,last_used_at=data.last_used_at,revoked_at=data.revoked_at,active=data.active,secret,feed_url=$"{baseUrl}/api/v2/events/calendar/personal/{Uri.EscapeDataString(slug)}/{secret}.ics"},new{secret_shown_once=true},Status:201);
    }

    public async Task<EventCalendarResult> RevokeAsync(int tenant,int userId,long tokenId,CancellationToken ct){if(await ActorAsync(tenant,userId,ct)is null)return Forbidden();var row=await _db.EventCalendarFeedTokens.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.UserId==userId&&x.Id==tokenId&&x.RevokedAt==null,ct);if(row is null)return new(null,Error:new("EVENT_CALENDAR_TOKEN_NOT_FOUND","Token not found",404));row.RevokedAt=DateTime.UtcNow;row.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync(ct);return new(new{revoked=true});}

    public async Task<(string? Ics, EventCalendarError? Error)> TenantFeedAsync(int tenant,int userId,DateOnly from,DateOnly to,string baseUrl,CancellationToken ct){var result=await CalendarAsync(tenant,userId,from,to,baseUrl,ct);if(!result.Succeeded)return(null,result.Error);var items=((IEnumerable<object>)result.Data!).Cast<object>().ToArray();return(Render(items,"Events"),null);}
    public async Task<(string? Ics, EventCalendarError? Error)> EventFeedAsync(int tenant,int userId,int eventId,string baseUrl,CancellationToken ct){var result=await EventAsync(tenant,userId,eventId,baseUrl,ct);return result.Succeeded?(Render([result.Data!],"Event"),null):(null,result.Error);}
    public async Task<(string? Ics, EventCalendarError? Error)> PersonalFeedAsync(string tenantSlug,string secret,string baseUrl,CancellationToken ct)
    {
        if(!System.Text.RegularExpressions.Regex.IsMatch(tenantSlug,"^[a-z0-9][a-z0-9-]{0,99}$")||!System.Text.RegularExpressions.Regex.IsMatch(secret,"^nxc_[a-f0-9]{64}$"))return(null,FeedMissing());var tenant=await _db.Tenants.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.Slug==tenantSlug&&x.IsActive,ct);if(tenant is null)return(null,FeedMissing());var token=await _db.EventCalendarFeedTokens.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant.Id&&x.TokenHash==Hash(secret)&&x.RevokedAt==null,ct);if(token is null)return(null,FeedMissing());var actor=await ActorAsync(tenant.Id,token.UserId,ct);if(actor is null)return(null,FeedMissing());var ids=await _db.EventRegistrations.IgnoreQueryFilters().Where(x=>x.TenantId==tenant.Id&&x.UserId==actor.Id&&x.RegistrationState=="confirmed").Select(x=>x.EventId).ToListAsync(ct);var now=DateTime.UtcNow;var events=await VisibleRangeAsync(tenant.Id,actor,now.AddDays(-30),now.AddDays(366),ids,ct);var changed=await _db.EventCalendarFeedTokens.IgnoreQueryFilters().Where(x=>x.Id==token.Id&&x.RevokedAt==null).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.LastUsedAt,DateTime.UtcNow).SetProperty(x=>x.UpdatedAt,DateTime.UtcNow),ct);return changed==1?(Render(events.Select(x=>Project(x,baseUrl)).Cast<object>().ToArray(),"My events"),null):(null,FeedMissing());
    }

    public object Actions(dynamic p){var start=DateTimeOffset.Parse((string)p.starts_at,CultureInfo.InvariantCulture);var end=DateTimeOffset.Parse((string)p.ends_at,CultureInfo.InvariantCulture);var dates=$"{start.UtcDateTime:yyyyMMdd'T'HHmmss'Z'}/{end.UtcDateTime:yyyyMMdd'T'HHmmss'Z'}";var google="https://calendar.google.com/calendar/r/eventedit?"+Query(new(){["action"]="TEMPLATE",["text"]=(string)p.title,["dates"]=dates,["details"]=(string)p.description,["stz"]=(string)p.timezone,["etz"]=(string)p.timezone});var outlook="https://outlook.office.com/calendar/deeplink/compose/?"+Query(new(){["path"]="/calendar/action/compose",["rru"]="addevent",["subject"]=(string)p.title,["startdt"]=(string)p.starts_at,["enddt"]=(string)p.ends_at,["body"]=(string)p.description});return new{google_url=google,outlook_url=outlook,download_path=$"/v2/events/{p.id}/calendar.ics"};}
    private async Task<List<Event>> VisibleRangeAsync(int tenant,User actor,DateTime from,DateTime to,List<int>? ids,CancellationToken ct){var q=_db.Events.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.PublicationStatus=="published"&&x.StartsAt<to&&(x.EndsAt==null?x.StartsAt>=from:x.EndsAt>from));if(ids is not null)q=q.Where(x=>ids.Contains(x.Id));var rows=await q.OrderBy(x=>x.StartsAt).ThenBy(x=>x.Id).ToListAsync(ct);var groups=await _db.GroupMembers.IgnoreQueryFilters().Where(x=>x.TenantId==tenant&&x.UserId==actor.Id&&x.Status=="active").Select(x=>x.GroupId).ToListAsync(ct);return rows.Where(x=>x.GroupId==null||groups.Contains(x.GroupId.Value)||x.CreatedById==actor.Id||IsAdmin(actor)).ToList();}
    private async Task<Event?> VisibleEventAsync(int tenant,User actor,int id,CancellationToken ct){var evt=await _db.Events.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.Id==id,ct);if(evt is null)return null;if(evt.PublicationStatus!="published"&&evt.CreatedById!=actor.Id&&!IsAdmin(actor))return null;if(evt.GroupId is int g&&evt.CreatedById!=actor.Id&&!IsAdmin(actor)&&!await _db.GroupMembers.IgnoreQueryFilters().AnyAsync(x=>x.TenantId==tenant&&x.GroupId==g&&x.UserId==actor.Id&&x.Status=="active",ct))return null;return evt;}
    private static dynamic Project(Event x,string baseUrl){var end=x.EndsAt??(x.AllDay?x.StartsAt.AddDays(1):x.StartsAt.AddHours(1));if(end<=x.StartsAt)end=x.StartsAt.AddHours(1);var operational=x.OperationalStatus is "scheduled" or "postponed" or "cancelled" or "completed"?x.OperationalStatus:x.IsCancelled?"cancelled":"scheduled";var seed=$"event|{x.TenantId}|{x.Id}|concrete";var detail=$"{baseUrl}/events/{x.Id}";return new{id=x.Id,uid=Hash(seed)[..40]+"@events.project-nexus.net",title=x.Title,description=$"View event details: {detail}",starts_at=x.AllDay?x.StartsAt.ToUniversalTime().ToString("yyyy-MM-dd"):x.StartsAt.ToUniversalTime().ToString("O"),ends_at=x.AllDay?end.ToUniversalTime().ToString("yyyy-MM-dd"):end.ToUniversalTime().ToString("O"),timezone=string.IsNullOrWhiteSpace(x.Timezone)?"UTC":x.Timezone,all_day=x.AllDay,operational_status=operational,calendar_status=operational=="cancelled"?"cancelled":operational=="postponed"?"tentative":"confirmed",sequence=Math.Max(0,x.CalendarSequence)+Math.Max(0,x.LifecycleVersion),updated_at=(x.UpdatedAt??x.CreatedAt).ToUniversalTime().ToString("O"),detail_url=detail};}
    private static string Render(object[] items,string name){var sb=new StringBuilder("BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Nexus//Timebank Platform//EN\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nX-WR-CALNAME:"+Esc(name)+"\r\n");foreach(dynamic x in items){var allDay=(bool)x.all_day;sb.Append("BEGIN:VEVENT\r\nUID:").Append(Esc((string)x.uid)).Append("\r\nDTSTAMP:").Append(DateTimeOffset.Parse((string)x.updated_at).UtcDateTime.ToString("yyyyMMdd'T'HHmmss'Z'")).Append("\r\nDTSTART").Append(allDay?";VALUE=DATE:":":").Append(IcsDate((string)x.starts_at,allDay)).Append("\r\nDTEND").Append(allDay?";VALUE=DATE:":":").Append(IcsDate((string)x.ends_at,allDay)).Append("\r\nSEQUENCE:").Append(x.sequence).Append("\r\nSTATUS:").Append((string)x.calendar_status=="cancelled"?"CANCELLED":(string)x.calendar_status=="tentative"?"TENTATIVE":"CONFIRMED").Append("\r\nSUMMARY:").Append(Esc((string)x.title)).Append("\r\nDESCRIPTION:").Append(Esc((string)x.description)).Append("\r\nURL:").Append(Esc((string)x.detail_url)).Append("\r\nEND:VEVENT\r\n");}return sb.Append("END:VCALENDAR\r\n").ToString();}
    private static object Token(EventCalendarFeedToken x)=>new{id=x.Id,label=x.Label,token_prefix=x.TokenPrefix,locale=x.Locale,created_at=Iso(x.CreatedAt),last_used_at=Iso(x.LastUsedAt),revoked_at=Iso(x.RevokedAt),active=x.RevokedAt==null};private async Task<User?> ActorAsync(int tenant,int user,CancellationToken ct)=>await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.Id==user&&x.IsActive,ct);private static string Locale(User x)=>"en";private static string Hash(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x))).ToLowerInvariant();private static string Esc(string x)=>x.Replace("\\","\\\\").Replace(";","\\;").Replace(",","\\,").Replace("\r","").Replace("\n","\\n");private static string IcsDate(string x,bool allDay)=>allDay?DateTime.Parse(x).ToString("yyyyMMdd"):DateTimeOffset.Parse(x).UtcDateTime.ToString("yyyyMMdd'T'HHmmss'Z'");private static string Query(Dictionary<string,string> x)=>string.Join("&",x.Select(kv=>$"{Uri.EscapeDataString(kv.Key)}={Uri.EscapeDataString(kv.Value)}"));private static string? Iso(DateTime? x)=>x?.ToUniversalTime().ToString("O");private static bool IsAdmin(User x)=>x.IsAdmin||x.IsSuperAdmin||x.IsTenantSuperAdmin||x.IsGod||x.Role is "admin" or "super_admin" or "god";private static EventCalendarResult Forbidden()=>new(null,Error:new("EVENT_CALENDAR_FORBIDDEN","Forbidden",403));private static EventCalendarResult Missing()=>new(null,Error:new("EVENT_NOT_FOUND","Event not found",404));private static EventCalendarResult RangeError()=>new(null,Error:new("EVENT_CALENDAR_RANGE_INVALID","Invalid range",422,"from"));private static EventCalendarError FeedMissing()=>new("EVENT_CALENDAR_FEED_NOT_FOUND","Feed not found",404);
}
