// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Nexus.Api.Data;
using Nexus.Api.Entities;

namespace Nexus.Api.Services;

public sealed record EventStaffError(string Code, string Message, int Status, string? Field = null);
public sealed record EventStaffResult(object? Data, object? Meta = null, EventStaffError? Error = null, int Status = 200) { public bool Succeeded => Error is null; }

public sealed class EventStaffService
{
    private static readonly Dictionary<string, string[]> Capabilities = new()
    {
        ["co_organizer"] = ["view","viewMeetingLink","viewRoster","viewWaitlist","manage","manageStaff","manageAttendance","messagePeople","exportPeople","linkSeries","manageRegistration","broadcast"],
        ["registration_manager"] = ["view","viewRoster","viewWaitlist","manageRegistration","exportPeople"],
        ["communications_manager"] = ["view","messagePeople","broadcast"],
        ["check_in_staff"] = ["view","viewRoster","manageAttendance"],
        ["finance_manager"] = ["view","manageFinance","reconcileCredits","reconcileTickets"],
    };
    private static readonly HashSet<string> Delegatable = ["registration_manager","communications_manager","check_in_staff"];
    private readonly NexusDbContext _db; public EventStaffService(NexusDbContext db) => _db = db;

    public async Task<EventStaffResult> ListAsync(int tenant, int eventId, int actorId, bool includeInactive, CancellationToken ct)
    {
        var context = await ContextAsync(tenant, eventId, actorId, ct); if (!context.Succeeded) return context;
        var rows = await _db.EventStaffAssignments.IgnoreQueryFilters().AsNoTracking().Include(x => x.History).Where(x => x.TenantId == tenant && x.EventId == eventId && (includeInactive || x.Status == "active" && (x.ExpiresAt == null || x.ExpiresAt > DateTime.UtcNow))).OrderBy(x => x.Role).ThenBy(x => x.UserId).ThenBy(x => x.Id).ToListAsync(ct);
        var projected = new List<object>(); foreach (var row in rows) projected.Add(await ProjectAsync(row, ct)); return new(projected, new { include_inactive = includeInactive, role_capabilities = Capabilities });
    }

    public async Task<EventStaffResult> GrantAsync(int tenant, int eventId, int actorId, int userId, string role, DateTime? expiry, string? key, CancellationToken ct)
    {
        expiry = expiry is null ? null : new DateTime(expiry.Value.ToUniversalTime().Ticks - expiry.Value.ToUniversalTime().Ticks % TimeSpan.TicksPerSecond, DateTimeKind.Utc);
        if (userId < 1) return Validation("user_id"); if (role == "owner") return new(null, Error: new("EVENT_STAFF_OWNER_ROLE_IMPLICIT", "Owner role is implicit", 422, "role")); if (!Capabilities.ContainsKey(role)) return Validation("role"); if (expiry is not null && expiry <= DateTime.UtcNow) return new(null, Error: new("EVENT_STAFF_EXPIRY_INVALID", "Expiry must be in the future", 422, "expires_at")); if (key is { Length: > 191 }) return Validation("idempotency_key");
        await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, actorId, ct); if (!context.Succeeded) return context; var (evt, actor, implicitAuthority, staffManager) = ((Event, User, bool, bool))context.Data!; if (!implicitAuthority && (!staffManager || !Delegatable.Contains(role))) return Forbidden(); if (evt.CreatedById == userId) return new(null, Error: new("EVENT_STAFF_OWNER_ROLE_IMPLICIT", "Owner role is implicit", 422, "role")); var target = await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.Id == userId && x.IsActive, ct); if (target is null) return new(null, Error: new("USER_NOT_FOUND", "User not found", 404, "user_id"));
        var replay = await ReplayAsync(tenant, eventId, userId, actorId, role, "granted", expiry, key, ct); if (replay is not null) { await tx.CommitAsync(ct); return replay; }
        var row = await _db.EventStaffAssignments.IgnoreQueryFilters().Include(x => x.History).SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == userId && x.Role == role, ct); if (row is not null && row.Status == "active" && Same(row.ExpiresAt, expiry)) { await tx.CommitAsync(ct); return new(new { assignment = await ProjectAsync(row, ct), changed = false, idempotent_replay = false, history_entry_id = (long?)null }); }
        var now = DateTime.UtcNow; var from = row?.Status; var oldExpiry = row?.ExpiresAt; if (row is null) { row = new() { TenantId = tenant, EventId = eventId, UserId = userId, Role = role, GrantedAt = now, GrantedBy = actorId, ExpiresAt = expiry }; _db.EventStaffAssignments.Add(row); } else { row.Status = "active"; row.AssignmentVersion++; row.GrantedAt = now; row.GrantedBy = actorId; row.RevokedAt = null; row.RevokedBy = null; row.ExpiresAt = expiry; row.UpdatedAt = now; } await _db.SaveChangesAsync(ct); var history = History(row, actorId, "granted", key, from, "active", oldExpiry, expiry, now); _db.EventStaffAssignmentHistory.Add(history); Outbox(row, actorId, "granted", now); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(new { assignment = await ProjectAsync(row, ct), changed = true, idempotent_replay = false, history_entry_id = history.Id }, Status: row.AssignmentVersion == 1 ? 201 : 200);
    }

    public async Task<EventStaffResult> RevokeAsync(int tenant, int eventId, long assignmentId, int actorId, string? key, CancellationToken ct)
    {
        if (assignmentId < 1) return MissingAssignment(); if (key is { Length: > 191 }) return Validation("idempotency_key"); await using var tx = await _db.Database.BeginTransactionAsync(ct); await LockAsync(tenant, eventId, ct); var context = await ContextAsync(tenant, eventId, actorId, ct); if (!context.Succeeded) return context; var (_, _, implicitAuthority, staffManager) = ((Event, User, bool, bool))context.Data!; var row = await _db.EventStaffAssignments.IgnoreQueryFilters().Include(x => x.History).SingleOrDefaultAsync(x => x.TenantId == tenant && x.EventId == eventId && x.Id == assignmentId, ct); if (row is null) return MissingAssignment(); if (!implicitAuthority && (!staffManager || !Delegatable.Contains(row.Role))) return Forbidden(); var replay = await ReplayAsync(tenant, eventId, row.UserId, actorId, row.Role, "revoked", null, key, ct); if (replay is not null) { await tx.CommitAsync(ct); return replay; } if (row.Status == "revoked") { await tx.CommitAsync(ct); return new(new { assignment = await ProjectAsync(row, ct), changed = false, idempotent_replay = false, history_entry_id = (long?)null }); }
        var now = DateTime.UtcNow; row.Status = "revoked"; row.AssignmentVersion++; row.RevokedAt = now; row.RevokedBy = actorId; row.UpdatedAt = now; var history = History(row, actorId, "revoked", key, "active", "revoked", row.ExpiresAt, row.ExpiresAt, now); _db.EventStaffAssignmentHistory.Add(history); Outbox(row, actorId, "revoked", now); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(new { assignment = await ProjectAsync(row, ct), changed = true, idempotent_replay = false, history_entry_id = history.Id });
    }

    private async Task<EventStaffResult> ContextAsync(int tenant, int eventId, int actorId, CancellationToken ct) { var evt = await _db.Events.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.Id == eventId, ct); if (evt is null) return new(null, Error: new("EVENT_NOT_FOUND", "Event not found", 404)); var actor = await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.Id == actorId && x.IsActive, ct); if (actor is null) return Forbidden(); var implicitAuthority = evt.CreatedById == actorId || IsAdmin(actor); var staffManager = await _db.EventStaffAssignments.IgnoreQueryFilters().AnyAsync(x => x.TenantId == tenant && x.EventId == eventId && x.UserId == actorId && x.Role == "co_organizer" && x.Status == "active" && (x.ExpiresAt == null || x.ExpiresAt > DateTime.UtcNow), ct); if (!implicitAuthority && !staffManager) return Forbidden(); return new((evt, actor, implicitAuthority, staffManager)); }
    private async Task<EventStaffResult?> ReplayAsync(int tenant, int eventId, int userId, int actorId, string role, string action, DateTime? expiry, string? key, CancellationToken ct) { if (string.IsNullOrWhiteSpace(key)) return null; var history = await _db.EventStaffAssignmentHistory.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenant && x.IdempotencyKey == key, ct); if (history is null) return null; if (history.EventId != eventId || history.UserId != userId || history.ActorUserId != actorId || history.Role != role || history.Action != action || action == "granted" && !Same(history.NewExpiresAt, expiry)) return new(null, Error: new("EVENT_STAFF_IDEMPOTENCY_CONFLICT", "Idempotency conflict", 409, "idempotency_key")); var row = await _db.EventStaffAssignments.IgnoreQueryFilters().AsNoTracking().Include(x => x.History).SingleAsync(x => x.Id == history.AssignmentId, ct); return new(new { assignment = await ProjectAsync(row, ct), changed = false, idempotent_replay = true, history_entry_id = history.Id }); }
    private async Task<object> ProjectAsync(EventStaffAssignment x, CancellationToken ct) { var user = await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleAsync(u => u.TenantId == x.TenantId && u.Id == x.UserId, ct); var history = x.History.OrderBy(h => h.AssignmentVersion).Select(h => new { id = h.Id, version = h.AssignmentVersion, action = h.Action, from_status = h.FromStatus, to_status = h.ToStatus, previous_expires_at = Iso(h.PreviousExpiresAt), new_expires_at = Iso(h.NewExpiresAt), actor_user_id = h.ActorUserId, idempotency_key = h.IdempotencyKey, metadata = JsonSerializer.Deserialize<Dictionary<string,object?>>(h.Metadata) ?? [], created_at = Iso(h.CreatedAt), immutable = true }).ToArray(); var latest = history.LastOrDefault(); return new { id = x.Id, event_id = x.EventId, member = new { id = user.Id, name = Name(user), first_name = user.FirstName, last_name = user.LastName, avatar_url = user.AvatarUrl }, role = x.Role, capabilities = Capabilities.GetValueOrDefault(x.Role, []), status = x.Status, effective = x.Status == "active" && (x.ExpiresAt == null || x.ExpiresAt > DateTime.UtcNow), version = x.AssignmentVersion, granted_at = Iso(x.GrantedAt), granted_by_user_id = x.GrantedBy, revoked_at = Iso(x.RevokedAt), revoked_by_user_id = x.RevokedBy, expires_at = Iso(x.ExpiresAt), history_metadata = new { immutable = true, entry_count = history.Length, latest_entry_id = latest?.id, latest_version = latest?.version }, history, created_at = Iso(x.CreatedAt), updated_at = Iso(x.UpdatedAt) }; }
    private static EventStaffAssignmentHistory History(EventStaffAssignment x, int actor, string action, string? key, string? from, string to, DateTime? oldExpiry, DateTime? newExpiry, DateTime now) => new() { TenantId = x.TenantId, EventId = x.EventId, AssignmentId = x.Id, UserId = x.UserId, Role = x.Role, ActorUserId = actor, AssignmentVersion = x.AssignmentVersion, Action = action, IdempotencyKey = string.IsNullOrWhiteSpace(key) ? null : key.Trim(), FromStatus = from, ToStatus = to, PreviousExpiresAt = oldExpiry, NewExpiresAt = newExpiry, Metadata = JsonSerializer.Serialize(new { schema_version = 1, source = "event_role_service", idempotency_key = key }), CreatedAt = now };
    private void Outbox(EventStaffAssignment x, int actor, string action, DateTime now) => _db.EventDomainOutbox.Add(new() { TenantId = x.TenantId, EventId = x.EventId, AggregateStream = "staff", AggregateVersion = x.AssignmentVersion, Action = $"event.staff_role.{action}", IdempotencyKey = $"event:{x.TenantId}:{x.EventId}:staff:{x.Id}:v{x.AssignmentVersion}", Payload = JsonSerializer.Serialize(new { schema_version = 1, tenant_id = x.TenantId, event_id = x.EventId, assignment_id = x.Id, assignment_version = x.AssignmentVersion, user_id = x.UserId, role = x.Role, action, actor_user_id = actor, occurred_at = now }), CreatedAt = now, UpdatedAt = now });
    private Task LockAsync(int tenant, int eventId, CancellationToken ct) => _db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock({tenant}, {eventId})", ct); private static bool Same(DateTime? a, DateTime? b) => a?.ToUniversalTime().Ticks == b?.ToUniversalTime().Ticks; private static string? Iso(DateTime? x) => x?.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ss'Z'"); private static string Name(User x) { var n = string.Join(' ', new[] { x.FirstName, x.LastName }.Where(s => !string.IsNullOrWhiteSpace(s))); return n.Length == 0 ? null! : n; } private static bool IsAdmin(User x) => x.IsAdmin || x.IsSuperAdmin || x.IsTenantSuperAdmin || x.IsGod || x.Role is "admin" or "super_admin" or "god"; private static EventStaffResult Forbidden() => new(null, Error: new("EVENT_STAFF_FORBIDDEN", "Forbidden", 403)); private static EventStaffResult Validation(string field) => new(null, Error: new("EVENT_STAFF_VALIDATION_FAILED", "Validation failed", 422, field)); private static EventStaffResult MissingAssignment() => new(null, Error: new("EVENT_STAFF_ASSIGNMENT_NOT_FOUND", "Assignment not found", 404));
}
