// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Nexus.Api.Data;
using Nexus.Api.Entities;
using NSec.Cryptography;

namespace Nexus.Api.Services;

public sealed record EventOfflineError(string Code,string Message,int Status,string? Field=null);
public sealed record EventOfflineResult(object? Data,EventOfflineError? Error=null,int Status=200){public bool Succeeded=>Error is null;}

public sealed class EventOfflineCheckinService : IDisposable
{
    private const int ReplayWindow=15, BatchMax=500; private static readonly HashSet<string> Operations=["check_in","check_out","no_show","undo"];
    private readonly NexusDbContext _db; private readonly Key _signingKey; private readonly string _kid; private readonly string _publicKey;
    public EventOfflineCheckinService(NexusDbContext db,IConfiguration config)
    {
        _db=db; var material=config["Jwt:Key"]??config["Jwt:Secret"]??"nexus-local-event-checkin-signing-boundary";
        var seed=SHA256.HashData(Encoding.UTF8.GetBytes(material+"|event-checkin-ed25519-v2"));
        _signingKey=Key.Import(SignatureAlgorithm.Ed25519,seed,KeyBlobFormat.RawPrivateKey);
        var pub=_signingKey.PublicKey.Export(KeyBlobFormat.RawPublicKey); _kid=HashBytes(pub)[..16]; _publicKey=B64(pub);
    }
    public void Dispose()=>_signingKey.Dispose();

    public async Task<EventOfflineResult> WorkspaceAsync(int tenant,int eventId,int actor,CancellationToken ct)
    {
        var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;
        var devices=await _db.EventCheckinDevices.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId).OrderByDescending(x=>x.Id).Take(50).ToListAsync(ct);
        var batches=await _db.EventOfflineSyncBatches.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId).OrderByDescending(x=>x.Id).Take(50).ToListAsync(ct);
        var ids=batches.Select(x=>x.Id).ToArray();var decisions=await _db.EventOfflineSyncDecisions.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&ids.Contains(x.BatchId)).ToListAsync(ct);
        var open=await OpenQuery(tenant,eventId).CountAsync(ct);
        return new(new{contract_version=1,event_id=eventId,occurrence_key=Occurrence(e),manifest_version=e.CheckinManifestVersion,limits=new{replay_window_minutes=ReplayWindow,batch_max_items=BatchMax},devices=devices.Select(Device),recent_batches=batches.Select(x=>BatchSummary(x,decisions.Where(d=>d.BatchId==x.Id))),open_conflicts=open,permissions=new{manage_devices=true,download_manifest=true,sync_offline_queue=true,resolve_conflicts=true,manual_fallback_required=true},privacy=new{device_secrets_redacted=true,credential_secrets_redacted=true,contact_fields_redacted=true,wallet_effects_supported=false}});
    }
    public async Task<EventOfflineResult> MyCredentialAsync(int tenant,int eventId,int actor,CancellationToken ct)
    {
        var c=await Context(tenant,eventId,actor,false,ct);if(!c.Succeeded)return c;var reg=await ConfirmedRegistration(tenant,eventId,actor,ct);if(reg is null)return Missing("EVENT_CHECKIN_REGISTRATION_NOT_FOUND");
        var row=await _db.EventCheckinCredentials.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId&&x.RegistrationId==reg.Id).OrderByDescending(x=>x.CredentialVersion).FirstOrDefaultAsync(ct);
        return new(new{contract_version=1,event_id=eventId,credential=row is null?null:Credential(row,null,false)});
    }
    public async Task<EventOfflineResult> IssueCredentialAsync(int tenant,int eventId,int actor,long? registrationId,string key,CancellationToken ct)
    {
        var k=ValidKey(key);if(k is not null)return k;await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var c=await Context(tenant,eventId,actor,false,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;
        var reg=registrationId is long id?await _db.EventRegistrations.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.Id==id&&x.RegistrationState=="confirmed",ct):await ConfirmedRegistration(tenant,eventId,actor,ct);if(reg is null)return Missing("EVENT_CHECKIN_REGISTRATION_NOT_FOUND");if(reg.UserId!=actor&&!await CanManage(tenant,e,actor,ct))return Forbidden();
        var kh=Hash(key);var replay=await _db.EventCheckinCredentials.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.IssueIdempotencyHash==kh,ct);if(replay is not null){if(replay.EventId!=eventId||replay.RegistrationId!=reg.Id||replay.IssuedByUserId!=actor)return Conflict("EVENT_CHECKIN_IDEMPOTENCY_CONFLICT");await tx.CommitAsync(ct);return CredentialResult(eventId,replay,null,e.CheckinManifestVersion,200);}
        var active=await _db.EventCheckinCredentials.IgnoreQueryFilters().AnyAsync(x=>x.TenantId==tenant&&x.RegistrationId==reg.Id&&x.Status=="active"&&x.ExpiresAt>DateTime.UtcNow,ct);if(active)return Conflict("EVENT_CHECKIN_CREDENTIAL_ACTIVE_EXISTS");
        var version=(await _db.EventCheckinCredentials.IgnoreQueryFilters().Where(x=>x.TenantId==tenant&&x.RegistrationId==reg.Id).MaxAsync(x=>(int?)x.CredentialVersion,ct)??0)+1;var expiry=Expiry(e);var token=SignedCredential(tenant,e,version,expiry);var row=new EventCheckinCredential{TenantId=tenant,EventId=eventId,RegistrationId=reg.Id,UserId=reg.UserId,CredentialVersion=version,TokenHash=Hash(token),TokenFingerprint=Hash(token)[..16],IssueIdempotencyHash=kh,IssuedByUserId=actor,ExpiresAt=expiry};_db.EventCheckinCredentials.Add(row);e.CheckinManifestVersion++;await _db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return CredentialResult(eventId,row,token,e.CheckinManifestVersion,201);
    }
    public async Task<EventOfflineResult> RotateCredentialAsync(int tenant,int eventId,long id,int actor,int expected,string key,CancellationToken ct)
    {
        var valid=ValidKey(key);if(valid is not null)return valid;await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var c=await Context(tenant,eventId,actor,false,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;var old=await _db.EventCheckinCredentials.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.Id==id,ct);if(old is null)return Missing();if(old.UserId!=actor&&!await CanManage(tenant,e,actor,ct))return Forbidden();var kh=Hash(key);var replay=await _db.EventCheckinCredentials.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.IssueIdempotencyHash==kh,ct);if(replay is not null){if(old.SupersededById!=replay.Id||old.CredentialVersion!=expected)return Conflict("EVENT_CHECKIN_IDEMPOTENCY_CONFLICT");await tx.CommitAsync(ct);return CredentialResult(eventId,replay,null,e.CheckinManifestVersion,200);}if(old.CredentialVersion!=expected||old.Status!="active")return Conflict();var expiry=Expiry(e);var token=SignedCredential(tenant,e,expected+1,expiry);var next=new EventCheckinCredential{TenantId=tenant,EventId=eventId,RegistrationId=old.RegistrationId,UserId=old.UserId,CredentialVersion=expected+1,TokenHash=Hash(token),TokenFingerprint=Hash(token)[..16],IssueIdempotencyHash=kh,IssuedByUserId=actor,ExpiresAt=expiry};old.Status="rotated";old.RotatedAt=DateTime.UtcNow;old.UpdatedAt=DateTime.UtcNow;_db.Add(next);await _db.SaveChangesAsync(ct);old.SupersededById=next.Id;e.CheckinManifestVersion++;await _db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return CredentialResult(eventId,next,token,e.CheckinManifestVersion,201);
    }
    public async Task<EventOfflineResult> RevokeCredentialAsync(int tenant,int eventId,long id,int actor,int expected,string? reason,CancellationToken ct)
    {var clean=Clean(reason,500);if(clean is null)return Validation("reason");await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var c=await Context(tenant,eventId,actor,false,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;var row=await _db.EventCheckinCredentials.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.Id==id,ct);if(row is null)return Missing();if(row.UserId!=actor&&!await CanManage(tenant,e,actor,ct))return Forbidden();if(row.CredentialVersion!=expected)return Conflict();if(row.Status!="revoked"){if(row.Status!="active")return Conflict();row.Status="revoked";row.RevokedByUserId=actor;row.RevokedAt=DateTime.UtcNow;row.RevocationReason=clean;row.UpdatedAt=DateTime.UtcNow;e.CheckinManifestVersion++;await _db.SaveChangesAsync(ct);}await tx.CommitAsync(ct);return CredentialResult(eventId,row,null,e.CheckinManifestVersion,200);}

    public async Task<EventOfflineResult> RegisterDeviceAsync(int tenant,int eventId,int actor,string? label,DateTime? expires,string key,CancellationToken ct)
    {var clean=Clean(label,120);if(clean is null)return Validation("label");var valid=ValidKey(key);if(valid is not null)return valid;await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;var kh=Hash(key);var replay=await _db.EventCheckinDevices.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.RegistrationIdempotencyHash==kh,ct);if(replay is not null){if(replay.EventId!=eventId||replay.RegisteredByUserId!=actor||replay.Label!=clean)return Conflict("EVENT_CHECKIN_IDEMPOTENCY_CONFLICT");await tx.CommitAsync(ct);return DeviceResult(eventId,replay,null,e.CheckinManifestVersion,200);}var secret=Secret("nxd1_");var expiry=expires?.ToUniversalTime()??Expiry(e);if(expiry<=DateTime.UtcNow||expiry>DateTime.UtcNow.AddDays(31))return Validation("expires_at");var row=new EventCheckinDevice{TenantId=tenant,EventId=eventId,Label=clean,RegisteredByUserId=actor,SecretHash=Hash(secret),SecretFingerprint=Hash(secret)[..16],RegistrationIdempotencyHash=kh,ExpiresAt=expiry};_db.Add(row);e.CheckinManifestVersion++;await _db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return DeviceResult(eventId,row,secret,e.CheckinManifestVersion,201);}
    public async Task<EventOfflineResult> RotateDeviceAsync(int tenant,int eventId,long id,int actor,int expected,string key,CancellationToken ct)
    {var valid=ValidKey(key);if(valid is not null)return valid;await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;var row=await _db.EventCheckinDevices.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.Id==id,ct);if(row is null)return Missing();var kh=Hash(key);if(row.LastRotationIdempotencyHash==kh){await tx.CommitAsync(ct);return DeviceResult(eventId,row,null,e.CheckinManifestVersion,200);}if(row.DeviceVersion!=expected||row.Status!="active")return Conflict();var secret=Secret("nxd1_");row.SecretHash=Hash(secret);row.SecretFingerprint=row.SecretHash[..16];row.DeviceVersion++;row.LastRotationIdempotencyHash=kh;row.RotatedAt=DateTime.UtcNow;row.UpdatedAt=DateTime.UtcNow;e.CheckinManifestVersion++;await _db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return DeviceResult(eventId,row,secret,e.CheckinManifestVersion,200);}
    public async Task<EventOfflineResult> RevokeDeviceAsync(int tenant,int eventId,long id,int actor,int expected,string? reason,CancellationToken ct)
    {var clean=Clean(reason,500);if(clean is null)return Validation("reason");await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;var row=await _db.EventCheckinDevices.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.Id==id,ct);if(row is null)return Missing();if(row.DeviceVersion!=expected)return Conflict();if(row.Status!="revoked"){if(row.Status!="active")return Conflict();row.Status="revoked";row.DeviceVersion++;row.RevokedByUserId=actor;row.RevokedAt=DateTime.UtcNow;row.RevocationReason=clean;row.UpdatedAt=DateTime.UtcNow;e.CheckinManifestVersion++;await _db.SaveChangesAsync(ct);}await tx.CommitAsync(ct);return DeviceResult(eventId,row,null,e.CheckinManifestVersion,200,true);}

    public async Task<EventOfflineResult> ManifestAsync(int tenant,int eventId,int actor,string secret,int? ttl,CancellationToken ct)
    {var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var e=(Event)c.Data!;var device=await DeviceBySecret(tenant,eventId,secret,ct);if(device is null)return UnauthorizedDevice();var minutes=Math.Clamp(ttl??120,5,720);var regs=await _db.EventRegistrations.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId&&x.RegistrationState=="confirmed").ToListAsync(ct);var ids=regs.Select(x=>x.Id).ToArray();var creds=await _db.EventCheckinCredentials.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId&&ids.Contains(x.RegistrationId)&&x.Status=="active"&&x.ExpiresAt>DateTime.UtcNow).ToListAsync(ct);var users=await _db.Users.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&regs.Select(r=>r.UserId).Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct);var attendance=await _db.EventAttendance.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId).ToDictionaryAsync(x=>x.UserId,ct);var now=DateTime.UtcNow;var rows=creds.Join(regs,x=>x.RegistrationId,x=>x.Id,(x,r)=>(x,r)).Select(z=>new{registration_id=z.r.Id,user_id=z.r.UserId,display_name=users.TryGetValue(z.r.UserId,out var u)?Name(u):"",credential_version=z.x.CredentialVersion,credential_fingerprint=z.x.TokenFingerprint,credential_verifier=z.x.TokenHash,attendance_status=attendance.TryGetValue(z.r.UserId,out var a)?a.AttendanceStatus:null,attendance_version=attendance.TryGetValue(z.r.UserId,out a)?a.AttendanceVersion:0});return new(new{schema_version=2,tenant_id=tenant,event_id=eventId,occurrence_key=Occurrence(e),manifest_version=e.CheckinManifestVersion,device=new{id=device.Id,version=device.DeviceVersion},generated_at=Iso(now),expires_at=Iso(now.AddMinutes(minutes)),credential_verification=new{format="nqx2",algorithm="Ed25519",keys=new[]{new{kid=_kid,alg="Ed25519",public_key=_publicKey}}},registrations=rows,privacy=new{credential_contains_pii=false,encrypted_at_rest_required=true}});}

    public async Task<EventOfflineResult> StageAsync(int tenant,int eventId,int actor,JsonElement body,CancellationToken ct)
    {
        if(!TryText(body,"device_secret",out var secret)||!TryText(body,"client_batch_id",out var clientId)||clientId.Length>191||!body.TryGetProperty("manifest_version",out var mv)||!mv.TryGetInt64(out var manifest)||!body.TryGetProperty("items",out var raw)||raw.ValueKind!=JsonValueKind.Array||raw.GetArrayLength()<1||raw.GetArrayLength()>BatchMax)return Validation("items");
        var device=await DeviceBySecret(tenant,eventId,secret,ct);if(device is null)return UnauthorizedDevice();
        var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;
        var payload=Hash(body.GetRawText());
        var replay=await _db.EventOfflineSyncBatches.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.DeviceId==device.Id&&x.ClientBatchId==clientId,ct);
        if(replay is not null){if(replay.PayloadHash!=payload)return Conflict("EVENT_CHECKIN_BATCH_IDEMPOTENCY_CONFLICT");return await BatchAsync(tenant,eventId,replay.Id,actor,ct);}

        var inputs=new List<EventOfflineSyncItem>();var pos=0;
        foreach(var x in raw.EnumerateArray())
        {
            pos++;
            if(!TryText(x,"client_nonce",out var nonce)||nonce.Length<8||nonce.Length>191||!TryText(x,"operation",out var op)||!Operations.Contains(op)||!TryDate(x,"observed_at",out var observed)||!TryLong(x,"expected_attendance_version",out var expected)||expected<0||!TryText(x,"credential_fingerprint",out var fp)||!Regex.IsMatch(fp,"^[0-9a-f]{16}$")||!TryText(x,"credential_hash_reference",out var href)||!Regex.IsMatch(href,"^[0-9a-f]{64}$")||!href.StartsWith(fp,StringComparison.Ordinal)||inputs.Any(i=>i.ClientNonce==nonce))return Validation("items");
            inputs.Add(new(){TenantId=tenant,EventId=eventId,DeviceId=device.Id,Position=pos,ClientNonce=nonce,Operation=op,ObservedAt=observed,ExpectedAttendanceVersion=expected,CredentialFingerprint=fp,CredentialHashReference=href,Reason=Clean(Text(x,"reason"),500)});
        }

        await using var tx=await _db.Database.BeginTransactionAsync(ct);
        await Lock(tenant,eventId,ct);
        var credentialEvaluatedAt=DateTime.UtcNow;
        var credentials=await ResolveCredentialSubjects(tenant,eventId,inputs,credentialEvaluatedAt,ct);
        var batch=new EventOfflineSyncBatch{TenantId=tenant,EventId=eventId,DeviceId=device.Id,SubmittedByUserId=actor,ClientBatchId=clientId,PayloadHash=payload,ManifestVersion=manifest,ItemCount=inputs.Count,Status="processing"};
        _db.Add(batch);await _db.SaveChangesAsync(ct);
        foreach(var item in inputs){item.BatchId=batch.Id;_db.Add(item);}
        await _db.SaveChangesAsync(ct);
        foreach(var item in inputs)
        {
            credentials.TryGetValue(item.CredentialFingerprint,out var credential);
            await DecideInitial(tenant,eventId,actor,item,credential,credentialEvaluatedAt,ct);
        }
        var ds=await _db.EventOfflineSyncDecisions.IgnoreQueryFilters().Where(x=>x.TenantId==tenant&&x.BatchId==batch.Id).ToListAsync(ct);
        batch.AcceptedCount=ds.Count(x=>x.Outcome=="accepted");batch.ConflictCount=ds.Count(x=>x.Outcome=="conflict");batch.RejectedCount=ds.Count(x=>x.Outcome=="rejected");batch.Status="completed";batch.CompletedAt=DateTime.UtcNow;
        await _db.SaveChangesAsync(ct);await tx.CommitAsync(ct);
        var result=await BatchAsync(tenant,eventId,batch.Id,actor,ct);return result with{Status=202};
    }
    public async Task<EventOfflineResult> BatchAsync(int tenant,int eventId,long id,int actor,CancellationToken ct){var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var batch=await _db.EventOfflineSyncBatches.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.Id==id,ct);if(batch is null)return Missing();var items=await _db.EventOfflineSyncItems.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.BatchId==id).OrderBy(x=>x.Position).ToListAsync(ct);var decisions=await _db.EventOfflineSyncDecisions.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.BatchId==id).ToListAsync(ct);return BatchResult(eventId,batch,items,decisions);}
    public async Task<EventOfflineResult> ConflictsAsync(int tenant,int eventId,int actor,int page,CancellationToken ct){var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;page=Math.Max(1,page);var all=await OpenQuery(tenant,eventId).ToListAsync(ct);var total=all.Count;var rows=all.OrderByDescending(x=>x.Decision.DecidedAt).Skip((page-1)*25).Take(25).ToList();var users=await _db.Users.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant).ToDictionaryAsync(x=>x.Id,ct);var devices=await _db.EventCheckinDevices.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId).ToDictionaryAsync(x=>x.Id,ct);var attendance=await _db.EventAttendance.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId).ToDictionaryAsync(x=>x.UserId,ct);return ConflictResult(eventId,rows,total,page,users,devices,attendance);}
    public async Task<EventOfflineResult> ResolveAsync(int tenant,int eventId,long itemId,int actor,int expectedDecision,string disposition,long expectedAttendance,string? reason,string key,CancellationToken ct)
    {if(disposition is not ("apply" or "reject")||expectedDecision<1||expectedAttendance<0||Clean(reason,500) is not string clean)return Validation("resolution");var valid=ValidKey(key);if(valid is not null)return valid;await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var item=await _db.EventOfflineSyncItems.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.Id==itemId,ct);if(item is null)return Missing();var latest=await _db.EventOfflineSyncDecisions.IgnoreQueryFilters().Where(x=>x.TenantId==tenant&&x.ItemId==itemId).OrderByDescending(x=>x.DecisionVersion).FirstAsync(ct);var kh=Hash(key);var replay=await _db.EventOfflineSyncDecisions.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.ResolutionIdempotencyHash==kh,ct);if(replay is not null){if(replay.ItemId!=itemId)return Conflict("EVENT_CHECKIN_IDEMPOTENCY_CONFLICT");await tx.CommitAsync(ct);return await ConflictsAsync(tenant,eventId,actor,1,ct);}if(latest.DecisionVersion!=expectedDecision||latest.Outcome!="conflict")return Conflict();var before=await AttendanceVersion(tenant,eventId,item.UserId,ct);if(before!=expectedAttendance)return Conflict();long? after=null,activity=null;var outcome="rejected";var code="manual_rejected";if(disposition=="apply"){var applied=await ApplyAttendance(tenant,eventId,actor,item,"offline-resolution:"+key,ct);if(!applied.Ok)return Conflict(applied.Code!);after=applied.After;activity=applied.Activity;outcome="accepted";code="manual_applied";}var next=new EventOfflineSyncDecision{TenantId=tenant,EventId=eventId,BatchId=item.BatchId,ItemId=item.Id,DecisionVersion=latest.DecisionVersion+1,Outcome=outcome,Code=code,Reason=clean,AttendanceVersionBefore=before,AttendanceVersionAfter=after,AttendanceActivityId=activity,DecidedByUserId=actor,ResolutionIdempotencyHash=kh};_db.Add(next);await _db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await ConflictsAsync(tenant,eventId,actor,1,ct);}
    public async Task<EventOfflineResult> ScanAsync(int tenant,int eventId,int actor,string deviceSecret,string token,string operation,long expected,string key,string? reason,CancellationToken ct)
    {var valid=ValidKey(key);if(valid is not null)return valid;if(!Operations.Contains(operation)||expected<0)return Validation("action");if(await DeviceBySecret(tenant,eventId,deviceSecret,ct) is null)return UnauthorizedDevice();if(string.IsNullOrWhiteSpace(token))return Missing("EVENT_CHECKIN_CREDENTIAL_INVALID");var hash=Hash(token);var cred=await _db.EventCheckinCredentials.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.TokenFingerprint==hash.Substring(0,16),ct);if(cred is null||!CryptographicOperations.FixedTimeEquals(Convert.FromHexString(cred.TokenHash),Convert.FromHexString(hash))||cred.Status!="active"||cred.ExpiresAt<=DateTime.UtcNow)return Missing("EVENT_CHECKIN_CREDENTIAL_INVALID");var c=await Context(tenant,eventId,actor,true,ct);if(!c.Succeeded)return c;var item=new EventOfflineSyncItem{TenantId=tenant,EventId=eventId,UserId=cred.UserId,RegistrationId=cred.RegistrationId,CredentialId=cred.Id,Operation=operation,ExpectedAttendanceVersion=expected,Reason=Clean(reason,500)};await using var tx=await _db.Database.BeginTransactionAsync(ct);await Lock(tenant,eventId,ct);var applied=await ApplyAttendance(tenant,eventId,actor,item,key,ct);if(!applied.Ok)return Conflict(applied.Code!);await tx.CommitAsync(ct);return new(new{contract_version=1,event_id=eventId,state="synced",attendance=new{user_id=cred.UserId,state=applied.State,version=applied.After},privacy=new{credential_redacted=true,wallet_effects_supported=false}});}

    private async Task<Dictionary<string,EventCheckinCredential>> ResolveCredentialSubjects(int tenant,int eventId,IEnumerable<EventOfflineSyncItem> items,DateTime evaluatedAt,CancellationToken ct)
    {
        var fingerprints=items.Select(x=>x.CredentialFingerprint).Distinct(StringComparer.Ordinal).ToArray();
        var credentials=await _db.EventCheckinCredentials.IgnoreQueryFilters().AsNoTracking().Where(x=>x.TenantId==tenant&&x.EventId==eventId&&fingerprints.Contains(x.TokenFingerprint)).ToListAsync(ct);
        var byFingerprint=credentials.GroupBy(x=>x.TokenFingerprint,StringComparer.Ordinal).ToDictionary(x=>x.Key,x=>x.Single(),StringComparer.Ordinal);
        foreach(var item in items)
        {
            if(!byFingerprint.TryGetValue(item.CredentialFingerprint,out var credential)||!IsUsableCredential(item,credential,evaluatedAt))continue;
            item.CredentialId=credential.Id;item.RegistrationId=credential.RegistrationId;item.UserId=credential.UserId;
        }
        return byFingerprint;
    }
    private async Task DecideInitial(int tenant,int eventId,int actor,EventOfflineSyncItem item,EventCheckinCredential? cred,DateTime credentialEvaluatedAt,CancellationToken ct)
    {
        string outcome,code;long before=await AttendanceVersion(tenant,eventId,cred?.UserId,ct);long? after=null,activity=null;
        if(!IsUsableCredential(item,cred,credentialEvaluatedAt)||item.CredentialId!=cred!.Id||item.RegistrationId!=cred.RegistrationId||item.UserId!=cred.UserId){outcome="rejected";code="credential_invalid";}
        else if(before!=item.ExpectedAttendanceVersion){outcome="conflict";code="attendance_version_conflict";}
        else
        {
            var applied=await ApplyAttendance(tenant,eventId,actor,item,$"offline:{item.DeviceId}:{item.ClientNonce}",ct);
            if(applied.Ok){outcome="accepted";code="synced";after=applied.After;activity=applied.Activity;}else{outcome="conflict";code=applied.Code!;}
        }
        _db.Add(new EventOfflineSyncDecision{TenantId=tenant,EventId=eventId,BatchId=item.BatchId,ItemId=item.Id,Outcome=outcome,Code=code,AttendanceVersionBefore=before,AttendanceVersionAfter=after,AttendanceActivityId=activity,DecidedByUserId=actor});await _db.SaveChangesAsync(ct);
    }
    private static bool IsUsableCredential(EventOfflineSyncItem item,EventCheckinCredential? credential,DateTime evaluatedAt)=>credential is not null&&credential.TokenHash==item.CredentialHashReference&&credential.Status=="active"&&credential.ExpiresAt>evaluatedAt;
    private async Task<(bool Ok,string? Code,long After,long? Activity,string State,bool Replay)> ApplyAttendance(int tenant,int eventId,int actor,EventOfflineSyncItem item,string key,CancellationToken ct){var existing=await _db.EventAttendanceActivity.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.IdempotencyKey==key,ct);if(existing is not null)return(true,null,existing.AttendanceVersion,existing.Id,existing.ToStatus,true);if(item.UserId is not int user)return(false,"credential_invalid",0,null,"",false);var fact=await _db.EventAttendance.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.EventId==eventId&&x.UserId==user,ct);var before=fact?.AttendanceVersion??0;if(before!=item.ExpectedAttendanceVersion)return(false,"attendance_version_conflict",before,null,fact?.AttendanceStatus??"not_checked_in",false);var from=fact?.AttendanceStatus??"not_checked_in";var to=item.Operation switch{"check_in" when from is "not_checked_in" or "no_show"=>"checked_in","check_out" when from=="checked_in"=>"checked_out","no_show" when from=="not_checked_in"=>"no_show","undo" when from is "checked_in" or "checked_out" or "no_show"=>"not_checked_in",_=>null};if(to is null)return(false,"attendance_transition_invalid",before,null,from,false);var now=DateTime.UtcNow;if(fact is null){fact=new EventAttendance{TenantId=tenant,EventId=eventId,UserId=user,AttendanceVersion=1,AttendanceStatus=to,StatusChangedAt=now,StatusChangedBy=actor};_db.Add(fact);}else{fact.AttendanceVersion++;fact.AttendanceStatus=to;fact.StatusChangedAt=now;fact.StatusChangedBy=actor;fact.UpdatedAt=now;}if(to=="checked_in"){fact.CheckedInAt=now;fact.CheckedInBy=actor;fact.CheckedOutAt=null;}else if(to=="checked_out")fact.CheckedOutAt=now;else if(to=="not_checked_in"){fact.CheckedInAt=null;fact.CheckedInBy=null;fact.CheckedOutAt=null;}await _db.SaveChangesAsync(ct);var activity=new EventAttendanceActivity{TenantId=tenant,EventId=eventId,AttendanceId=fact.Id,UserId=user,ActorUserId=actor,AttendanceVersion=fact.AttendanceVersion,Action=item.Operation,FromStatus=from,ToStatus=to,IdempotencyKey=key,Reason=item.Reason,Metadata=JsonSerializer.Serialize(new{source="offline_checkin"})};_db.Add(activity);await _db.SaveChangesAsync(ct);return(true,null,fact.AttendanceVersion,activity.Id,to,false);}
    private IQueryable<ConflictJoin> OpenQuery(int tenant,int eventId)=>from i in _db.EventOfflineSyncItems.IgnoreQueryFilters() join b in _db.EventOfflineSyncBatches.IgnoreQueryFilters() on i.BatchId equals b.Id join d in _db.EventOfflineSyncDecisions.IgnoreQueryFilters() on i.Id equals d.ItemId where i.TenantId==tenant&&i.EventId==eventId&&d.Outcome=="conflict"&&!_db.EventOfflineSyncDecisions.IgnoreQueryFilters().Any(n=>n.TenantId==tenant&&n.ItemId==i.Id&&n.DecisionVersion>d.DecisionVersion) select new ConflictJoin(i,b,d);
    private async Task<EventOfflineResult> Context(int tenant,int eventId,int actor,bool manager,CancellationToken ct){var e=await _db.Events.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.Id==eventId,ct);if(e is null)return Missing();var u=await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenant&&x.Id==actor&&x.IsActive,ct);if(u is null)return Forbidden();if(manager&&!await CanManage(tenant,e,actor,ct))return Forbidden();return new(e);}
    private async Task<bool> CanManage(int tenant,Event e,int actor,CancellationToken ct){var u=await _db.Users.IgnoreQueryFilters().AsNoTracking().SingleAsync(x=>x.TenantId==tenant&&x.Id==actor,ct);if(IsAdmin(u)||e.CreatedById==actor)return true;return await _db.EventStaffAssignments.IgnoreQueryFilters().AnyAsync(x=>x.TenantId==tenant&&x.EventId==e.Id&&x.UserId==actor&&x.Status=="active"&&(x.ExpiresAt==null||x.ExpiresAt>DateTime.UtcNow)&&(x.Role=="check_in_staff"||x.Role=="event_manager"||x.Role=="co_organizer"),ct);}
    private Task<EventRegistration?> ConfirmedRegistration(int t,int e,int u,CancellationToken ct)=>_db.EventRegistrations.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==t&&x.EventId==e&&x.UserId==u&&x.RegistrationState=="confirmed",ct);
    private async Task<EventCheckinDevice?> DeviceBySecret(int t,int e,string secret,CancellationToken ct){if(!Regex.IsMatch(secret,"^nxd1_[A-Za-z0-9_-]{43}$"))return null;var hash=Hash(secret);return await _db.EventCheckinDevices.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TenantId==t&&x.EventId==e&&x.SecretFingerprint==hash.Substring(0,16)&&x.SecretHash==hash&&x.Status=="active"&&x.ExpiresAt>DateTime.UtcNow,ct);}
    private Task Lock(int t,int e,CancellationToken ct)=>_db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock({t}, {e})",ct);private async Task<long> AttendanceVersion(int t,int e,int? u,CancellationToken ct)=>u is null?0:await _db.EventAttendance.IgnoreQueryFilters().Where(x=>x.TenantId==t&&x.EventId==e&&x.UserId==u).Select(x=>(long?)x.AttendanceVersion).SingleOrDefaultAsync(ct)??0;
    private EventOfflineResult BatchResult(int eventId,EventOfflineSyncBatch b,IEnumerable<EventOfflineSyncItem> items,IEnumerable<EventOfflineSyncDecision> decisions)=>new(new{contract_version=1,event_id=eventId,batch=new{id=b.Id,client_batch_id=b.ClientBatchId,status=b.Status,item_count=b.ItemCount,accepted_count=b.AcceptedCount,conflict_count=b.ConflictCount,rejected_count=b.RejectedCount,created_at=Iso(b.CreatedAt),completed_at=IsoN(b.CompletedAt)},items=items.Select(i=>{var d=decisions.Where(x=>x.ItemId==i.Id).OrderByDescending(x=>x.DecisionVersion).FirstOrDefault();return new{id=i.Id,position=i.Position,client_nonce=i.ClientNonce,operation=i.Operation,observed_at=Iso(i.ObservedAt),expected_attendance_version=i.ExpectedAttendanceVersion,state=d?.Outcome switch{"accepted"=>"synced","conflict"=>"conflict","rejected"=>"rejected",_=>"pending"},decision_version=(int?)d?.DecisionVersion,code=d?.Code,reason=d?.Reason??i.Reason,decided_at=IsoN(d?.DecidedAt)};}),privacy=new{credential_redacted=true,attendee_identity_redacted=true}});
    private EventOfflineResult ConflictResult(int eventId,IEnumerable<ConflictJoin> rows,int total,int page,Dictionary<int,User> users,Dictionary<long,EventCheckinDevice> devices,Dictionary<int,EventAttendance> attendance)=>new(new{contract_version=1,event_id=eventId,items=rows.Select(x=>new{item_id=x.Item.Id,batch_id=x.Batch.Id,client_batch_id=x.Batch.ClientBatchId,member=new{id=x.Item.UserId!.Value,display_name=users.TryGetValue(x.Item.UserId.Value,out var u)?Name(u):""},operation=x.Item.Operation,observed_at=Iso(x.Item.ObservedAt),submitted_reason=x.Item.Reason,expected_attendance_version=x.Item.ExpectedAttendanceVersion,current_attendance=new{state=attendance.TryGetValue(x.Item.UserId.Value,out var a)?a.AttendanceStatus:"not_checked_in",version=attendance.TryGetValue(x.Item.UserId.Value,out a)?a.AttendanceVersion:0},conflict=new{decision_version=x.Decision.DecisionVersion,code=x.Decision.Code!,decided_at=Iso(x.Decision.DecidedAt)},device=new{id=x.Batch.DeviceId,label=devices.TryGetValue(x.Batch.DeviceId,out var d)?d.Label:null}}),total,page,per_page=25,privacy=new{credential_redacted=true,contact_fields_redacted=true,free_text_member_profile_redacted=true}});
    private static object Credential(EventCheckinCredential x,string? token,bool oneShot)=>new{id=x.Id,registration_id=x.RegistrationId,version=x.CredentialVersion,status=x.Status,expires_at=Iso(x.ExpiresAt),revoked_at=IsoN(x.RevokedAt),token,token_one_shot=oneShot,contains_pii=false};private static EventOfflineResult CredentialResult(int e,EventCheckinCredential x,string? token,long mv,int status)=>new(new{contract_version=1,event_id=e,credential=Credential(x,token,token is not null),manifest_version=mv},Status:status);
    private static object Device(EventCheckinDevice x)=>new{id=x.Id,public_id=x.PublicId,label=x.Label,registered_by_user_id=x.RegisteredByUserId,version=x.DeviceVersion,status=x.Status,registered_at=Iso(x.RegisteredAt),expires_at=Iso(x.ExpiresAt),rotated_at=IsoN(x.RotatedAt),revoked_at=IsoN(x.RevokedAt),revocation_reason=x.RevocationReason};private static EventOfflineResult DeviceResult(int e,EventCheckinDevice x,string? secret,long mv,int status,bool purge=false)=>new(new{contract_version=1,event_id=e,device=new{id=x.Id,public_id=x.PublicId,label=x.Label,version=x.DeviceVersion,status=x.Status,expires_at=Iso(x.ExpiresAt),revoked_at=IsoN(x.RevokedAt),secret,secret_one_shot=secret is not null,purge_local_data_required=purge},manifest_version=mv},Status:status);
    private static object BatchSummary(EventOfflineSyncBatch x,IEnumerable<EventOfflineSyncDecision> ds)=>new{id=x.Id,device_id=x.DeviceId,client_batch_id=x.ClientBatchId,manifest_version=x.ManifestVersion,item_count=x.ItemCount,status=x.Status,counts=new{synced=ds.Count(d=>d.Outcome=="accepted"),conflict=ds.Count(d=>d.Outcome=="conflict"),rejected=ds.Count(d=>d.Outcome=="rejected"),pending=Math.Max(0,x.ItemCount-ds.Count())},created_at=Iso(x.CreatedAt),completed_at=IsoN(x.CompletedAt),dead_lettered_at=IsoN(x.DeadLetteredAt),terminal_code=x.TerminalCode};
    private string SignedCredential(int tenant,Event e,int version,DateTime expiry){var now=DateTimeOffset.UtcNow;var claims=JsonSerializer.Serialize(new SortedDictionary<string,object>{{"alg","Ed25519"},{"aud","event-checkin"},{"evt",e.Id},{"exp",new DateTimeOffset(expiry).ToUnixTimeSeconds()},{"iat",now.ToUnixTimeSeconds()},{"jti",B64(RandomNumberGenerator.GetBytes(16))},{"kid",_kid},{"occ",Hash(Occurrence(e))},{"ten",tenant},{"v",2},{"ver",version}});var encoded=B64(Encoding.UTF8.GetBytes(claims));var sig=SignatureAlgorithm.Ed25519.Sign(_signingKey,Encoding.ASCII.GetBytes(encoded));return "nqx2_"+encoded+"."+B64(sig);}
    private static DateTime Expiry(Event e){var end=e.EndsAt?.ToUniversalTime()??e.StartsAt.ToUniversalTime().AddHours(12);var expiry=end.AddHours(24);return expiry>DateTime.UtcNow.AddMinutes(5)?expiry:DateTime.UtcNow.AddHours(24);}private static string Occurrence(Event e)=>$"event:{e.Id}:{e.StartsAt.ToUniversalTime():O}";private static string Secret(string p)=>p+B64(RandomNumberGenerator.GetBytes(32));private static string Hash(string x)=>HashBytes(Encoding.UTF8.GetBytes(x));private static string HashBytes(byte[] x)=>Convert.ToHexString(SHA256.HashData(x)).ToLowerInvariant();private static string B64(byte[] x)=>Convert.ToBase64String(x).TrimEnd('=').Replace('+','-').Replace('/','_');private static string Iso(DateTime x)=>x.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ss'Z'");private static string? IsoN(DateTime? x)=>x is null?null:Iso(x.Value);private static string Name(User u)=>string.Join(' ',new[]{u.FirstName,u.LastName}.Where(x=>!string.IsNullOrWhiteSpace(x)));private static bool IsAdmin(User x)=>x.IsAdmin||x.IsSuperAdmin||x.IsTenantSuperAdmin||x.IsGod||x.Role is "admin" or "super_admin" or "god";
    private static string? Clean(string? x,int max){if(string.IsNullOrWhiteSpace(x))return null;var v=Regex.Replace(Regex.Replace(x,"<[^>]*>",""),"[\\x00-\\x1F\\x7F]"," ");v=Regex.Replace(v,"\\s+"," ").Trim();return v.Length is >0&&v.Length<=max?v:null;}private static string? Text(JsonElement x,string n)=>x.TryGetProperty(n,out var p)&&p.ValueKind==JsonValueKind.String?p.GetString():null;private static bool TryText(JsonElement x,string n,out string value){value=Text(x,n)?.Trim()??"";return value.Length>0;}private static bool TryLong(JsonElement x,string n,out long value){value=0;return x.TryGetProperty(n,out var p)&&p.TryGetInt64(out value);}private static bool TryDate(JsonElement x,string n,out DateTime value){value=default;return TryText(x,n,out var s)&&DateTimeOffset.TryParse(s,out var d)&&(value=d.UtcDateTime)!=default;}
    private static EventOfflineResult? ValidKey(string key)=>string.IsNullOrWhiteSpace(key)||key.Trim().Length<8||key.Trim().Length>191?Validation("idempotency_key"):null;private static EventOfflineResult Missing(string code="EVENT_CHECKIN_NOT_FOUND")=>new(null,new(code,"Event check-in resource not found",404));private static EventOfflineResult Forbidden()=>new(null,new("EVENT_CHECKIN_FORBIDDEN","Forbidden",403));private static EventOfflineResult UnauthorizedDevice()=>new(null,new("EVENT_CHECKIN_DEVICE_INVALID","Device credential is invalid",401));private static EventOfflineResult Conflict(string code="EVENT_CHECKIN_CONFLICT")=>new(null,new(code,"Version or state conflict",409));private static EventOfflineResult Validation(string field)=>new(null,new("EVENT_CHECKIN_VALIDATION_FAILED","Validation failed",422,field));
    private sealed record ConflictJoin(EventOfflineSyncItem Item,EventOfflineSyncBatch Batch,EventOfflineSyncDecision Decision);
}
