// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

namespace Nexus.Api.Entities;

/// <summary>
/// A computed match between two users (and optionally a listing).
/// Generated by the matching engine and stored for the user to review.
/// </summary>
public class MatchResult : ITenantEntity
{
    public int Id { get; set; }
    public int TenantId { get; set; }

    /// <summary>
    /// The user this match was generated for.
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// The other user who was matched.
    /// </summary>
    public int MatchedUserId { get; set; }

    /// <summary>
    /// The listing that triggered/relates to this match, if any.
    /// </summary>
    public int? MatchedListingId { get; set; }

    /// <summary>
    /// Match quality score from 0.0 (no match) to 1.0 (perfect match).
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// JSON array of reasons explaining the score, e.g.
    /// ["skill_overlap:gardening","category_match:home_services","high_rating:4.8"]
    /// </summary>
    public string? Reasons { get; set; }

    /// <summary>
    /// Current status of this match from the user's perspective.
    /// </summary>
    public MatchStatus Status { get; set; } = MatchStatus.Pending;

    /// <summary>
    /// When the user first viewed this match.
    /// </summary>
    public DateTime? ViewedAt { get; set; }

    /// <summary>
    /// When the user accepted or declined this match.
    /// </summary>
    public DateTime? RespondedAt { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    // Navigation properties
    public Tenant? Tenant { get; set; }
    public User? User { get; set; }
    public User? MatchedUser { get; set; }
    public Listing? MatchedListing { get; set; }
}

/// <summary>
/// Lifecycle states for a match result.
/// </summary>
public enum MatchStatus
{
    /// <summary>Match has been computed but not yet viewed.</summary>
    Pending,
    /// <summary>User has viewed the match details.</summary>
    Viewed,
    /// <summary>User has accepted/expressed interest in this match.</summary>
    Accepted,
    /// <summary>User has declined this match.</summary>
    Declined,
    /// <summary>Match has expired (e.g., listing no longer available).</summary>
    Expired
}
