using System;
// Copyright (c) 2024-2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nexus.Api.Migrations
{
    /// <inheritdoc />
    public partial class AdminVolunteerApprovalWorkflow : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // VolunteerAdminExtras was historically recorded with an empty Up()
            // even though its model snapshot introduced this table. Existing
            // databases may have received it out-of-band; fresh EF chains did
            // not. Bootstrap only when absent so both histories converge before
            // adding the new opportunity/expiry fields below.
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS volunteer_guardian_consents (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "TenantId" integer NOT NULL,
                    "MinorUserId" integer NOT NULL,
                    "GuardianName" character varying(200) NOT NULL,
                    "GuardianEmail" character varying(320) NOT NULL,
                    "GuardianRelationship" character varying(100),
                    "ConsentedAt" timestamp with time zone,
                    "RevokedAt" timestamp with time zone,
                    "ConsentDocumentUrl" character varying(2000),
                    "Status" character varying(20) NOT NULL,
                    "ReviewerNote" character varying(500),
                    "ReviewedByUserId" integer,
                    "ReviewedAt" timestamp with time zone,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "PK_volunteer_guardian_consents" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_volunteer_guardian_consents_tenants_TenantId"
                        FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_volunteer_guardian_consents_users_MinorUserId"
                        FOREIGN KEY ("MinorUserId") REFERENCES users ("Id") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS "IX_volunteer_guardian_consents_MinorUserId"
                    ON volunteer_guardian_consents ("MinorUserId");
                CREATE INDEX IF NOT EXISTS "IX_volunteer_guardian_consents_Status"
                    ON volunteer_guardian_consents ("Status");
                CREATE INDEX IF NOT EXISTS "IX_volunteer_guardian_consents_TenantId"
                    ON volunteer_guardian_consents ("TenantId");
                """);

            migrationBuilder.DropIndex(
                name: "IX_volunteer_applications_TenantId_OpportunityId_UserId",
                table: "volunteer_applications");

            migrationBuilder.DropIndex(
                name: "IX_ShiftGroupReservations_TenantId",
                table: "ShiftGroupReservations");

            migrationBuilder.AddColumn<DateTime>(
                name: "ExpiresAt",
                table: "volunteer_guardian_consents",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "OpportunityId",
                table: "volunteer_guardian_consents",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "OrgNote",
                table: "volunteer_applications",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "ShiftId",
                table: "volunteer_applications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Link",
                table: "notifications",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_volunteer_guardian_consents_OpportunityId",
                table: "volunteer_guardian_consents",
                column: "OpportunityId");

            migrationBuilder.CreateIndex(
                name: "IX_volunteer_guardian_consents_TenantId_MinorUserId_Status_Opp~",
                table: "volunteer_guardian_consents",
                columns: new[] { "TenantId", "MinorUserId", "Status", "OpportunityId", "ExpiresAt" });

            migrationBuilder.CreateIndex(
                name: "IX_volunteer_applications_ShiftId",
                table: "volunteer_applications",
                column: "ShiftId");

            migrationBuilder.CreateIndex(
                name: "IX_volunteer_applications_TenantId_OpportunityId_UserId",
                table: "volunteer_applications",
                columns: new[] { "TenantId", "OpportunityId", "UserId" });

            migrationBuilder.CreateIndex(
                name: "IX_volunteer_applications_TenantId_ShiftId_Status",
                table: "volunteer_applications",
                columns: new[] { "TenantId", "ShiftId", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_ShiftGroupReservations_TenantId_ShiftId_Status",
                table: "ShiftGroupReservations",
                columns: new[] { "TenantId", "ShiftId", "Status" });

            migrationBuilder.AddForeignKey(
                name: "FK_volunteer_applications_volunteer_shifts_ShiftId",
                table: "volunteer_applications",
                column: "ShiftId",
                principalTable: "volunteer_shifts",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_volunteer_guardian_consents_volunteer_opportunities_Opportu~",
                table: "volunteer_guardian_consents",
                column: "OpportunityId",
                principalTable: "volunteer_opportunities",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Up permits legitimate declined/withdrawn application history for
            // the same tenant/opportunity/user. Restoring the former unique index
            // could fail after valid use or require silent data loss, so fail
            // before dropping any new constraints or columns.
            throw new NotSupportedException(
                "AdminVolunteerApprovalWorkflow is intentionally irreversible because restoring the former unique volunteer-application index is not data-safe.");
        }
    }
}
