// Copyright (c) 2024-2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nexus.Api.Migrations;

    [Microsoft.EntityFrameworkCore.Infrastructure.DbContext(typeof(Nexus.Api.Data.NexusDbContext))]
    [Microsoft.EntityFrameworkCore.Migrations.Migration("20260709202500_AddUserBlocks")]
    public partial class AddUserBlocks : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS user_blocks (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id integer NOT NULL REFERENCES tenants("Id") ON DELETE RESTRICT,
                user_id integer NOT NULL REFERENCES users("Id") ON DELETE CASCADE,
                blocked_user_id integer NOT NULL REFERENCES users("Id") ON DELETE CASCADE,
                reason text NULL,
                created_at timestamp with time zone NOT NULL DEFAULT now()
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_blocks_tenant_user_blocked"
                ON user_blocks (tenant_id, user_id, blocked_user_id);

            CREATE INDEX IF NOT EXISTS "IX_user_blocks_tenant_user"
                ON user_blocks (tenant_id, user_id);

            CREATE INDEX IF NOT EXISTS "IX_user_blocks_tenant_blocked"
                ON user_blocks (tenant_id, blocked_user_id);

            CREATE INDEX IF NOT EXISTS "IX_user_blocks_UserId"
                ON user_blocks (user_id);

            CREATE INDEX IF NOT EXISTS "IX_user_blocks_BlockedUserId"
                ON user_blocks (blocked_user_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS user_blocks;");
    }
}
