using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nexus.Api.Migrations
{
    /// <summary>
    /// Creates the scheduled_job_runs table. The entity + EF configuration
    /// + model-snapshot entry were added with Phase 63, but no migration was
    /// ever generated to actually create the table. Result: every
    /// ScheduledHostedService tick (14 jobs, ~every 1-30min) attempts an
    /// INSERT against a non-existent relation and Sentry has been ingesting
    /// the EF "Failed executing DbCommand" event hundreds of times per day.
    ///
    /// Idempotent CREATE so it is safe to re-apply on environments where the
    /// table was hand-created out of band.
    ///
    /// Fixes DOTNET-ASPNETCORE-2, DOTNET-ASPNETCORE-3, DOTNET-ASPNETCORE-4,
    /// DOTNET-ASPNETCORE-5, DOTNET-ASPNETCORE-6, DOTNET-ASPNETCORE-7.
    /// </summary>
    public partial class AddScheduledJobRuns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS scheduled_job_runs (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TenantId"" integer NULL,
                    ""JobName"" character varying(100) NOT NULL,
                    ""StartedAt"" timestamp with time zone NOT NULL,
                    ""CompletedAt"" timestamp with time zone NULL,
                    ""Status"" character varying(20) NOT NULL,
                    ""ItemsProcessed"" integer NOT NULL DEFAULT 0,
                    ""ErrorMessage"" character varying(2000) NULL,
                    ""ErrorType"" text NULL,
                    ""DurationMs"" double precision NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_scheduled_job_runs_JobName""
                    ON scheduled_job_runs (""JobName"");
                CREATE INDEX IF NOT EXISTS ""IX_scheduled_job_runs_StartedAt""
                    ON scheduled_job_runs (""StartedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_scheduled_job_runs_JobName_StartedAt""
                    ON scheduled_job_runs (""JobName"", ""StartedAt"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "scheduled_job_runs");
        }
    }
}
