// Copyright (c) 2024-2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nexus.Api.Migrations;

public partial class AddUserSafeguardingPreferences : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS user_safeguarding_preferences (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId" integer NOT NULL REFERENCES tenants("Id") ON DELETE RESTRICT,
                "UserId" integer NOT NULL REFERENCES users("Id") ON DELETE CASCADE,
                "OptionId" integer NOT NULL REFERENCES safeguarding_options("Id") ON DELETE RESTRICT,
                "SelectedValue" character varying(120) NOT NULL DEFAULT 'true',
                "Notes" character varying(2000) NULL,
                "ConsentGivenAt" timestamp with time zone NULL,
                "ConsentIp" character varying(64) NULL,
                "RevokedAt" timestamp with time zone NULL,
                "ReviewReminderSentAt" timestamp with time zone NULL,
                "ReviewConfirmedAt" timestamp with time zone NULL,
                "ReviewEscalatedAt" timestamp with time zone NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAt" timestamp with time zone NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_user_safeguarding_preferences_tenant_user_option_revoked"
                ON user_safeguarding_preferences ("TenantId", "UserId", "OptionId", "RevokedAt");

            CREATE INDEX IF NOT EXISTS "IX_user_safeguarding_preferences_tenant_review_reminder"
                ON user_safeguarding_preferences ("TenantId", "ReviewReminderSentAt");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS user_safeguarding_preferences;");
    }
}
