// Copyright (c) 2024-2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nexus.Api.Data;

#nullable disable

namespace Nexus.Api.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260704031800_AddCaringKpiBaselines")]
    partial class AddCaringKpiBaselines
    {
    }
}
